//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpacerHotKeys.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpacerHotKeys.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset   ^R;57600
        ///Open ZEN ...   ^O;57601
        ///Open Mesh ...;32931
        ///Merge ZEN ...   ^M;32847
        ///Merge Mesh ...;32932
        ///Save ZEN ...   ^S;32938
        ///Save Mesh ...;32939
        ///Quick Save To tmp ...   Alt+S;32973
        ///Quick Open From tmp   Alt+O;32972
        ///Exit;57665
        ///Recent File;57616
        ///Console   ^F1;32904
        ///View Textoutput   ALT+O;33035
        ///View Informations   ALT+I;33036
        ///Toggle Sound;32990
        ///Toggle Invisible Vobs   I;32837
        ///Boundingboxes   B;33016
        ///Waynet   W;32991
        ///Cam-Splines;33032
        ///Wireframe;32850
        ///Fogging   F;32833
        ///Bilinear Filter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MenuResources {
            get {
                return ResourceManager.GetString("MenuResources", resourceCulture);
            }
        }
    }
}
