ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:54
user HornOx
END
objects 14       
END

[% zCMaterial 17408 0]
	name=string:OWODWATRGRASSMIMOUNTAINFAR
	matGroup=enum:2
	color=color:56 56 53 255
	smoothAngle=float:60
	texture=string:OWODWATRGRASSMIMOUNTAINFAR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:OWODWATRGRASSMIMOUNTAINFAR01
	matGroup=enum:2
	color=color:61 60 53 255
	smoothAngle=float:60
	texture=string:OWODWATRGRASSMIMOUNTAINFAR01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:OWODWATRGRASSMIMOUNTAINCLOSE
	matGroup=enum:2
	color=color:69 66 53 255
	smoothAngle=float:60
	texture=string:OWODWATRGRASSMIMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:OWODWAGRASSDASLOP
	matGroup=enum:4
	color=color:88 79 49 255
	smoothAngle=float:60
	texture=string:OWODWAGRASSDASLOP.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:OWODWAGRASSMISLOP
	matGroup=enum:4
	color=color:90 80 52 255
	smoothAngle=float:60
	texture=string:OWODWAGRASSMISLOP.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:OWODWAGRASSMIMOUNTAINCLOSE2
	matGroup=enum:4
	color=color:73 68 53 255
	smoothAngle=float:60
	texture=string:OWODWAGRASSMIMOUNTAINCLOSE2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:OWODWATRMOUNTAINCLOSEUNDERWATER
	matGroup=enum:2
	color=color:54 50 37 255
	smoothAngle=float:60
	texture=string:OWODWATRMOUNTAINCLOSEUNDERWATER.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:OWODWATRGRASSMIUNDERWATER
	matGroup=enum:4
	color=color:74 66 37 255
	smoothAngle=float:60
	texture=string:OWODWATRGRASSMIUNDERWATER.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:NCODWATRWOODGRASS
	matGroup=enum:3
	color=color:59 55 34 255
	smoothAngle=float:60
	texture=string:NCODWATRWOODGRASS.TGA
	texScale=string:128 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:NCODWATRROCKSTONE
	matGroup=enum:2
	color=color:59 61 50 255
	smoothAngle=float:60
	texture=string:NCODWATRROCKSTONE.TGA
	texScale=string:256 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:OWODWAGRASSLIMOUNTAINCLOSE
	matGroup=enum:2
	color=color:68 63 50 255
	smoothAngle=float:60
	texture=string:OWODWAGRASSLIMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:OWODWATRGRASS2
	matGroup=enum:2
	color=color:69 66 53 255
	smoothAngle=float:60
	texture=string:OWODWATRGRASSMIMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:NCODWACHAOSWOOD
	matGroup=enum:3
	color=color:58 51 37 255
	smoothAngle=float:60
	texture=string:NCODWACHAOSWOOD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:AL_W_DEF_IN_UP
	matGroup=enum:3
	color=color:65 56 52 255
	smoothAngle=float:60
	texture=string:AL_W_DEF_IN_UP.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
