ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:54
user HornOx
END
objects 39       
END

[% zCMaterial 17408 0]
	name=string:OWODWATSTOP
	matGroup=enum:5
	color=color:72 93 101 200
	smoothAngle=float:100
	texture=string:OWODSEA_A0.TGA
	texScale=string:64 64
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:OWODWATSTAND
	matGroup=enum:5
	color=color:72 93 101 200
	smoothAngle=float:100
	texture=string:OWODWAT_A0.TGA
	texScale=string:64 64
	texAniFPS=float:7
	texAniMapMode=enum:1
	texAniMapDir=string:0 -2.9999999e-005
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:OWODWFALL2SEA
	matGroup=enum:5
	color=color:160 179 185 200
	smoothAngle=float:100
	texture=string:OWODWFALL2SEA_A0.TGA
	texScale=string:256 256
	texAniFPS=float:20.000021
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:OWODWFALL_HITSURFACE
	matGroup=enum:5
	color=color:48 50 52 255
	smoothAngle=float:100
	texture=string:OWODWFALL_HITSURFACE_A0.TGA
	texScale=string:256 256
	texAniFPS=float:10.0000105
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:OWODWATFAST
	matGroup=enum:5
	color=color:72 93 101 200
	smoothAngle=float:100
	texture=string:OWODWAT_A0.TGA
	texScale=string:256 256
	texAniFPS=float:10.0000105
	texAniMapMode=enum:1
	texAniMapDir=string:0 -0.00030000001
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:OWODSEA2SWAMP
	matGroup=enum:5
	color=color:54 67 60 220
	smoothAngle=float:100
	texture=string:OWODSEA2SWAMP_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:OWODWFALL
	matGroup=enum:5
	color=color:149 165 172 240
	smoothAngle=float:100
	texture=string:OWODWFALL_A0.TGA
	texScale=string:256 256
	texAniFPS=float:10.0000105
	texAniMapMode=enum:1
	texAniMapDir=string:0 -0.001
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:OWODWFALLFASTWATER
	matGroup=enum:5
	color=color:149 165 172 220
	smoothAngle=float:100
	texture=string:OWODWFALL_A0.TGA
	texScale=string:256 256
	texAniFPS=float:10.0000105
	texAniMapMode=enum:1
	texAniMapDir=string:0 -0.00050000002
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:NCWASSER
	matGroup=enum:5
	color=color:72 93 101 200
	smoothAngle=float:60
	texture=string:OWODWAT_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:OCFLWAT
	matGroup=enum:5
	color=color:72 93 101 220
	smoothAngle=float:60
	texture=string:OWODWAT_A0.TGA
	texScale=string:256 256
	texAniFPS=float:4
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:OWODWFALL_STONE
	matGroup=enum:5
	color=color:24 24 25 255
	smoothAngle=float:100
	texture=string:OWODWFALL_STONE_A0.TGA
	texScale=string:256 256
	texAniFPS=float:10.0000105
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:TPL_LAVA_A0
	matGroup=enum:0
	color=color:255 153 0 255
	smoothAngle=float:60
	texture=string:TPL_LAVA_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000238
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:MAGBA
	matGroup=enum:0
	color=color:36 151 145 255
	smoothAngle=float:60
	texture=string:MAGBA_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000286
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:FLSWAMPLI          
	matGroup=enum:5
	color=color:35 39 19 220
	smoothAngle=float:45
	texture=string:SWAMP_A0.TGA
	texScale=string:256 256
	texAniFPS=float:4
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:OLD_BRACKWASSER_PUNKT_DE
	matGroup=enum:5
	color=color:54 49 26 230
	smoothAngle=float:60
	texture=string:PCODFLSWAMP01.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000525
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:ZF1_A0
	matGroup=enum:0
	color=color:19 17 15 255
	smoothAngle=float:60
	texture=string:ZF1_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:BIRDFLY_A0
	matGroup=enum:0
	color=color:8 23 116 255
	smoothAngle=float:60
	texture=string:BIRDFLY_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:ELECTRIC_A0
	matGroup=enum:0
	color=color:5 5 5 255
	smoothAngle=float:60
	texture=string:ELECTRIC_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:FIRE_COMPLETE_A0
	matGroup=enum:0
	color=color:22 14 5 255
	smoothAngle=float:60
	texture=string:FIRE_COMPLETE_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:FIREBALL16BIT_A0
	matGroup=enum:0
	color=color:113 98 66 255
	smoothAngle=float:60
	texture=string:FIREBALL16BIT_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:FLASH_A0
	matGroup=enum:0
	color=color:92 103 109 255
	smoothAngle=float:60
	texture=string:FLASH_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:GREENBLUR_A0
	matGroup=enum:0
	color=color:43 81 33 255
	smoothAngle=float:60
	texture=string:GREENBLUR_A0.TGA
	texScale=string:256 256
	texAniFPS=float:4
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 22]
	name=string:LEAF_A0
	matGroup=enum:0
	color=color:1 2 1 255
	smoothAngle=float:60
	texture=string:LEAF_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 23]
	name=string:LIGHTBOLT16BIT_A0
	matGroup=enum:0
	color=color:52 17 67 255
	smoothAngle=float:60
	texture=string:LIGHTBOLT16BIT_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 24]
	name=string:LIGHTBOLT_A0
	matGroup=enum:0
	color=color:52 17 67 255
	smoothAngle=float:60
	texture=string:LIGHTBOLT_A0.TGA
	texScale=string:256 256
	texAniFPS=float:6
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 25]
	name=string:LIGHTNING_BIG_A0
	matGroup=enum:0
	color=color:36 55 79 255
	smoothAngle=float:60
	texture=string:LIGHTNING_BIG_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 26]
	name=string:LIGHTNING_ORIGIN_A0
	matGroup=enum:0
	color=color:69 76 102 255
	smoothAngle=float:60
	texture=string:LIGHTNING_ORIGIN_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 27]
	name=string:LIGHTNINGNEU_BIG_A0
	matGroup=enum:0
	color=color:36 55 79 255
	smoothAngle=float:60
	texture=string:LIGHTNINGNEU_BIG_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 28]
	name=string:MAGICFRONTIER_A0
	matGroup=enum:0
	color=color:38 65 69 255
	smoothAngle=float:60
	texture=string:MAGICFRONTIER_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 29]
	name=string:MFX_FIRERAIN_RAIN_BIG_A0
	matGroup=enum:0
	color=color:62 42 20 255
	smoothAngle=float:60
	texture=string:MFX_FIRERAIN_RAIN_BIG_A0.TGA
	texScale=string:256 256
	texAniFPS=float:6
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 30]
	name=string:OTWADEMONEYE_A0
	matGroup=enum:0
	color=color:50 22 7 255
	smoothAngle=float:60
	texture=string:OTWADEMONEYE_A0.TGA
	texScale=string:256 256
	texAniFPS=float:6
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 31]
	name=string:RING_A0
	matGroup=enum:0
	color=color:1 1 1 255
	smoothAngle=float:60
	texture=string:RING_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 32]
	name=string:THUNDER_A0
	matGroup=enum:0
	color=color:48 48 61 255
	smoothAngle=float:60
	texture=string:THUNDER_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 33]
	name=string:UNDERWATER_A0
	matGroup=enum:0
	color=color:14 13 12 255
	smoothAngle=float:60
	texture=string:UNDERWATER_A0.TGA
	texScale=string:256 256
	texAniFPS=float:3
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 34]
	name=string:UW_PARTICLES_A0
	matGroup=enum:0
	color=color:0 0 0 255
	smoothAngle=float:60
	texture=string:UW_PARTICLES_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 35]
	name=string:WASSERRINGE_A0
	matGroup=enum:0
	color=color:4 6 7 255
	smoothAngle=float:60
	texture=string:WASSERRINGE_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 36]
	name=string:WATERFALL_A0
	matGroup=enum:0
	color=color:83 89 90 255
	smoothAngle=float:60
	texture=string:WATERFALL_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 37]
	name=string:WATERRING_A0
	matGroup=enum:0
	color=color:4 6 7 255
	smoothAngle=float:60
	texture=string:WATERRING_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 38]
	name=string:WHITEFOG_A0
	matGroup=enum:0
	color=color:237 237 237 255
	smoothAngle=float:60
	texture=string:WHITEFOG_A0.TGA
	texScale=string:256 256
	texAniFPS=float:5.00000095
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
