ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:55
user HornOx
END
objects 172      
END

[% zCMaterial 17408 0]
	name=string:ORKODFLFLOOR06
	matGroup=enum:0
	color=color:41 34 28 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:ORKODFLTRFLOORFLOOR3
	matGroup=enum:0
	color=color:39 33 25 255
	smoothAngle=float:60
	texture=string:ORKODFLTRFLOORFLOOR3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:ORKODFLFLOOR05
	matGroup=enum:0
	color=color:41 34 28 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:ORKODTRFLOOR05FLOOR03
	matGroup=enum:0
	color=color:37 32 27 255
	smoothAngle=float:60
	texture=string:ORKODTRFLOOR05FLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:ORKODTRFLOOR11
	matGroup=enum:0
	color=color:47 43 35 255
	smoothAngle=float:60
	texture=string:ORKODTRFLOOR16FLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:ORKODTRFLOOR01
	matGroup=enum:0
	color=color:37 32 27 255
	smoothAngle=float:60
	texture=string:ORKODTRFLOOR05FLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:OTFLTILE04
	matGroup=enum:0
	color=color:90 77 58 255
	smoothAngle=float:60
	texture=string:OTFLTILE05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:OCIDWAHUTCEILING
	matGroup=enum:0
	color=color:62 54 41 255
	smoothAngle=float:60
	texture=string:OCIDWAHUTCEILING.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:NCODFLDIRT
	matGroup=enum:4
	color=color:80 76 65 255
	smoothAngle=float:60
	texture=string:NCODFLDIRT.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:OMWATRWALL03
	matGroup=enum:0
	color=color:59 57 45 255
	smoothAngle=float:60
	texture=string:OMWATRWALL03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:OMWATRFLOOR02
	matGroup=enum:0
	color=color:60 56 46 255
	smoothAngle=float:60
	texture=string:OMWATRFLOOR02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:OMWATRFLOOR04
	matGroup=enum:0
	color=color:72 68 57 255
	smoothAngle=float:60
	texture=string:OMWATRFLOOR04.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:OMWATRFLOOR05
	matGroup=enum:0
	color=color:70 68 54 255
	smoothAngle=float:60
	texture=string:OMWATRFLOOR05.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:OMWATRWALL031
	matGroup=enum:0
	color=color:59 57 45 255
	smoothAngle=float:60
	texture=string:OMWATRWALL03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:OMWATRFLOOR021
	matGroup=enum:0
	color=color:60 56 46 255
	smoothAngle=float:60
	texture=string:OMWATRFLOOR02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:NCODFLGREY01
	matGroup=enum:2
	color=color:60 56 46 255
	smoothAngle=float:60
	texture=string:NCODFLGREY01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:OMWATRFLOORWALL09
	matGroup=enum:0
	color=color:64 61 48 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL09.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:OMWATRFLOORWALL06
	matGroup=enum:0
	color=color:60 62 56 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:OMWATRFLOORWALL03
	matGroup=enum:0
	color=color:58 56 46 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:OMWATRFLOOR01
	matGroup=enum:0
	color=color:63 62 56 255
	smoothAngle=float:60
	texture=string:OMWATRFLOOR01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:OMWATRFLOORWALL02
	matGroup=enum:0
	color=color:61 56 44 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:OMWATRFLOOR03
	matGroup=enum:0
	color=color:62 64 56 255
	smoothAngle=float:60
	texture=string:OMWATRFLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 22]
	name=string:OMWATRWALL02
	matGroup=enum:0
	color=color:63 60 46 255
	smoothAngle=float:60
	texture=string:OMWATRWALL02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 23]
	name=string:OMWATRFLOORWALL07
	matGroup=enum:0
	color=color:63 61 53 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL07.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 24]
	name=string:OMWATRFLOORWALL01
	matGroup=enum:0
	color=color:81 78 69 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 25]
	name=string:OMWATRWALL01
	matGroup=enum:0
	color=color:73 68 55 255
	smoothAngle=float:60
	texture=string:OMWATRWALL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 26]
	name=string:OMWATRFLOORWALL10
	matGroup=enum:0
	color=color:64 59 47 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL10.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 27]
	name=string:OMWATRFLOORWALL11
	matGroup=enum:0
	color=color:61 56 44 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL11.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 28]
	name=string:OCODFLROUGHSTONE
	matGroup=enum:0
	color=color:41 45 29 255
	smoothAngle=float:60
	texture=string:OCODFLROUGHSTONE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 29]
	name=string:OWODFLSTRAND
	matGroup=enum:4
	color=color:159 137 103 255
	smoothAngle=float:60
	texture=string:OWODFLSTRAND.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 30]
	name=string:OWODFLUNDERWATER
	matGroup=enum:4
	color=color:53 47 24 255
	smoothAngle=float:60
	texture=string:OWODFLUNDERWATER.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 31]
	name=string:OWODFLGRASSMI
	matGroup=enum:4
	color=color:91 81 52 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 32]
	name=string:OWODFLGRASSMIMOUNTAINFAR
	matGroup=enum:4
	color=color:79 71 49 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMIMOUNTAINFAR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 33]
	name=string:OWODPAIGRASSMI
	matGroup=enum:4
	color=color:101 88 63 255
	smoothAngle=float:60
	texture=string:OWODPAIGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 34]
	name=string:OWODFLGRASSMIMOUNTAINFARCLOSE
	matGroup=enum:4
	color=color:76 70 53 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMIMOUNTAINFARCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 35]
	name=string:PCODFLSWAMP01
	matGroup=enum:4
	color=color:54 49 26 255
	smoothAngle=float:60
	texture=string:PCODFLSWAMP01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 36]
	name=string:OWODFLGRASSDA
	matGroup=enum:4
	color=color:76 72 35 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 37]
	name=string:OWODFLGRASSDAWOOD
	matGroup=enum:4
	color=color:75 66 36 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSDAWOOD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 38]
	name=string:NCODFLSAND
	matGroup=enum:4
	color=color:99 89 75 255
	smoothAngle=float:60
	texture=string:NCODFLSAND.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 39]
	name=string:OTFLTILE01
	matGroup=enum:4
	color=color:70 66 54 255
	smoothAngle=float:60
	texture=string:OTFLTILE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 40]
	name=string:OCODFLSTONEFLOORMI
	matGroup=enum:2
	color=color:70 66 52 255
	smoothAngle=float:60
	texture=string:OCODFLSTONEFLOORMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 41]
	name=string:NCODFLGREY04
	matGroup=enum:2
	color=color:93 90 82 255
	smoothAngle=float:45
	texture=string:NCODFLGREY04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 42]
	name=string:OCODFLDARKDIR1
	matGroup=enum:0
	color=color:38 41 22 255
	smoothAngle=float:60
	texture=string:OCODFLDARKDIRTSTONE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 43]
	name=string:OTFLTILE021
	matGroup=enum:0
	color=color:64 62 50 255
	smoothAngle=float:60
	texture=string:OTFLTILE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 44]
	name=string:OWODPAIGRASSDA
	matGroup=enum:4
	color=color:87 81 46 255
	smoothAngle=float:60
	texture=string:OWODPAIGRASSDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 45]
	name=string:OCODFLDARKDIRTSTONE
	matGroup=enum:2
	color=color:38 41 22 255
	smoothAngle=float:60
	texture=string:OCODFLDARKDIRTSTONE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 46]
	name=string:OWODFLTRGRASSDAUNDERWATER01
	matGroup=enum:4
	color=color:127 112 77 255
	smoothAngle=float:60
	texture=string:OWODFLTRGRASSDAUNDERWATER01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 47]
	name=string:OWODPATRGRASSMIWOOD
	matGroup=enum:4
	color=color:92 80 56 255
	smoothAngle=float:60
	texture=string:OWODPATRGRASSMIWOOD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 48]
	name=string:OWODPAIENDGRASSDA
	matGroup=enum:4
	color=color:81 75 42 255
	smoothAngle=float:60
	texture=string:OWODPAIENDGRASSDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 49]
	name=string:OWODFLTRGRASSDAUNDERWATER02
	matGroup=enum:4
	color=color:133 115 83 255
	smoothAngle=float:60
	texture=string:OWODFLTRGRASSDAUNDERWATER02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 50]
	name=string:OWODFLWOODGROUND
	matGroup=enum:4
	color=color:70 55 32 255
	smoothAngle=float:60
	texture=string:OWODFLWOODGROUND.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 51]
	name=string:OWODFLLIGHTGROUNDGEROLL
	matGroup=enum:4
	color=color:71 63 43 255
	smoothAngle=float:60
	texture=string:OWODFLLIGHTGROUNDGEROLL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 52]
	name=string:OWODPAWOODGROUND
	matGroup=enum:4
	color=color:79 66 43 255
	smoothAngle=float:60
	texture=string:OWODPAWOODGROUND.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 53]
	name=string:PCODFLSWAMP012
	matGroup=enum:0
	color=color:54 49 26 255
	smoothAngle=float:60
	texture=string:PCODFLSWAMP01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 54]
	name=string:PCODWAROCK
	matGroup=enum:2
	color=color:53 57 36 255
	smoothAngle=float:60
	texture=string:PCODWAROCK.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 55]
	name=string:PCODFLSWAMP02
	matGroup=enum:4
	color=color:50 51 27 255
	smoothAngle=float:60
	texture=string:PCODFLSWAMP02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 56]
	name=string:PCODWALSWAMP01
	matGroup=enum:4
	color=color:68 63 38 255
	smoothAngle=float:60
	texture=string:PCODWALSWAMP01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 57]
	name=string:PCIDFLBODEN01
	matGroup=enum:3
	color=color:73 68 40 255
	smoothAngle=float:60
	texture=string:PCIDFLBODEN01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 58]
	name=string:PCODWATRROCKHUT
	matGroup=enum:2
	color=color:47 52 32 255
	smoothAngle=float:60
	texture=string:PCODWATRROCKHUT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 59]
	name=string:PSI_STEG_TABLE_02
	matGroup=enum:0
	color=color:58 54 26 255
	smoothAngle=float:60
	texture=string:PCODWATREE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 60]
	name=string:PCODWALSWAMP01END
	matGroup=enum:4
	color=color:62 57 33 255
	smoothAngle=float:60
	texture=string:PCODWALSWAMP01END.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 61]
	name=string:PCODWALSWAMP01TCROSS
	matGroup=enum:4
	color=color:70 65 40 255
	smoothAngle=float:60
	texture=string:PCODWALSWAMP01TCROSS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 62]
	name=string:PCODFLSWAMP013
	matGroup=enum:0
	color=color:54 49 26 255
	smoothAngle=float:60
	texture=string:PCODFLSWAMP01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 63]
	name=string:OWODFLGRASSLI
	matGroup=enum:4
	color=color:75 67 50 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSLI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 64]
	name=string:OWODFLTRGRASSLIDA
	matGroup=enum:4
	color=color:75 69 43 255
	smoothAngle=float:60
	texture=string:OWODFLTRGRASSLIDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 65]
	name=string:OTPATILE1
	matGroup=enum:2
	color=color:78 73 59 255
	smoothAngle=float:60
	texture=string:OTPATILE1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 66]
	name=string:OWODFLTRGRASSMIDA
	matGroup=enum:4
	color=color:83 76 43 255
	smoothAngle=float:60
	texture=string:OWODFLTRGRASSMIDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 67]
	name=string:OCODFLRING
	matGroup=enum:4
	color=color:67 61 39 255
	smoothAngle=float:60
	texture=string:OCODFLRING.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 68]
	name=string:OWODPAIMOUNTAINCLOSE
	matGroup=enum:2
	color=color:73 68 55 255
	smoothAngle=float:60
	texture=string:OWODPAIMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 69]
	name=string:OWODFLGRASSMI2
	matGroup=enum:4
	color=color:91 81 52 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 70]
	name=string:OWODPAIENDEGR1
	matGroup=enum:4
	color=color:97 88 61 255
	smoothAngle=float:60
	texture=string:OWODPAIENDEGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 71]
	name=string:OWODPAIGRASSM1
	matGroup=enum:4
	color=color:101 88 63 255
	smoothAngle=float:60
	texture=string:OWODPAIGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 72]
	name=string:OCODFLGRAS
	matGroup=enum:4
	color=color:76 72 35 255
	smoothAngle=float:60
	texture=string:OCODFLGRAS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 73]
	name=string:OCODFLLIGHTGROUNDLI
	matGroup=enum:4
	color=color:72 63 40 255
	smoothAngle=float:60
	texture=string:OCODFLLIGHTGROUNDLI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 74]
	name=string:OWODFLGRASSDA1
	matGroup=enum:4
	color=color:76 72 35 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 75]
	name=string:OWODPAIENDEGRASSMI
	matGroup=enum:4
	color=color:97 88 61 255
	smoothAngle=float:60
	texture=string:OWODPAIENDEGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 76]
	name=string:OCODFLLIGHTGROUNDDA
	matGroup=enum:4
	color=color:83 73 49 255
	smoothAngle=float:60
	texture=string:OCODFLLIGHTGROUNDDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 77]
	name=string:OWODPATGRASSMI
	matGroup=enum:4
	color=color:107 93 70 255
	smoothAngle=float:60
	texture=string:OWODPATGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 78]
	name=string:OWODFLGRASSMIMOUNTAINCLOSE
	matGroup=enum:4
	color=color:73 65 45 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMIMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 79]
	name=string:OWODFLGRASSMIWOOD
	matGroup=enum:4
	color=color:82 70 44 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMIWOOD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 80]
	name=string:OCODFLTRGRASSDIRT
	matGroup=enum:4
	color=color:87 76 49 255
	smoothAngle=float:60
	texture=string:OCODFLTRGRASSDIRT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 81]
	name=string:OCODPATGRAS
	matGroup=enum:4
	color=color:92 83 53 255
	smoothAngle=float:60
	texture=string:OCODPATGRAS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 82]
	name=string:OCODFLSAND
	matGroup=enum:4
	color=color:105 92 67 255
	smoothAngle=float:60
	texture=string:OCODFLSAND.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 83]
	name=string:OCODPAIGRAS
	matGroup=enum:4
	color=color:87 80 48 255
	smoothAngle=float:60
	texture=string:OCODPAIGRAS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 84]
	name=string:OCODPALGRAS
	matGroup=enum:4
	color=color:86 79 47 255
	smoothAngle=float:60
	texture=string:OCODPALGRAS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 85]
	name=string:OCODPAXGRAS
	matGroup=enum:4
	color=color:96 86 58 255
	smoothAngle=float:60
	texture=string:OCODPAXGRAS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 86]
	name=string:OWODFLGRASSMI3
	matGroup=enum:4
	color=color:91 81 52 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 87]
	name=string:ORKODFLFLOOR03
	matGroup=enum:2
	color=color:35 31 26 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 88]
	name=string:OWODTRGRASSMILI
	matGroup=enum:4
	color=color:83 74 51 255
	smoothAngle=float:60
	texture=string:OWODTRGRASSMILI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 89]
	name=string:OWODPATGRASSDA
	matGroup=enum:4
	color=color:90 81 52 255
	smoothAngle=float:60
	texture=string:OWODPATGRASSDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 90]
	name=string:NCODPASTONEMUD
	matGroup=enum:2
	color=color:80 72 51 255
	smoothAngle=float:60
	texture=string:NCODPASTONEMUD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 91]
	name=string:NCODWABROWNSTONE
	matGroup=enum:2
	color=color:82 69 50 255
	smoothAngle=float:60
	texture=string:NCODWABROWNSTONE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 92]
	name=string:NCODFLGRASDA
	matGroup=enum:5
	color=color:68 65 37 170
	smoothAngle=float:60
	texture=string:NCODFLGRASDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 93]
	name=string:NCODFLGRAS
	matGroup=enum:4
	color=color:91 78 49 255
	smoothAngle=float:60
	texture=string:NCODFLGRAS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 94]
	name=string:NCODPALIGHTROCKI
	matGroup=enum:2
	color=color:88 77 60 255
	smoothAngle=float:60
	texture=string:NCODPALIGHTROCKI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 95]
	name=string:NCIDWAROOF011
	matGroup=enum:0
	color=color:81 69 54 255
	smoothAngle=float:60
	texture=string:NCIDWAROOF01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 96]
	name=string:NCODFLTRLAKESIDE
	matGroup=enum:4
	color=color:78 70 52 255
	smoothAngle=float:60
	texture=string:NCODFLTRLAKESIDE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 97]
	name=string:NCIDWAROOF01
	matGroup=enum:3
	color=color:81 69 54 255
	smoothAngle=float:60
	texture=string:NCIDWAROOF01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 98]
	name=string:NCIDFLFELL
	matGroup=enum:2
	color=color:71 70 59 255
	smoothAngle=float:60
	texture=string:NCIDFLFELL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 99]
	name=string:NCODWAGREY04
	matGroup=enum:2
	color=color:83 81 70 255
	smoothAngle=float:60
	texture=string:NCODWAGREY04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 100]
	name=string:NCODPAMEDIUMROCKI
	matGroup=enum:2
	color=color:87 81 68 255
	smoothAngle=float:60
	texture=string:NCODPAMEDIUMROCKI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 101]
	name=string:NCODFLGREY02
	matGroup=enum:2
	color=color:59 57 50 255
	smoothAngle=float:60
	texture=string:NCODFLGREY02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 102]
	name=string:NCODWADARKROCK01
	matGroup=enum:2
	color=color:88 84 68 255
	smoothAngle=float:60
	texture=string:NCODWADARKROCK01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 103]
	name=string:NCODPAGREYROCKI01
	matGroup=enum:2
	color=color:65 61 49 255
	smoothAngle=float:60
	texture=string:NCODPAGREYROCKI01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 104]
	name=string:NCODPADARKROCKI
	matGroup=enum:2
	color=color:92 88 72 255
	smoothAngle=float:60
	texture=string:NCODPADARKROCKI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 105]
	name=string:NCODFLGREY03
	matGroup=enum:2
	color=color:60 56 46 255
	smoothAngle=float:60
	texture=string:NCODFLGREY03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 106]
	name=string:NCODWADARKROCKHOLE
	matGroup=enum:2
	color=color:69 64 54 255
	smoothAngle=float:60
	texture=string:NCODWADARKROCKHOLE.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 107]
	name=string:OCODWADARKSTONEEDGE
	matGroup=enum:2
	color=color:51 52 36 255
	smoothAngle=float:60
	texture=string:OCODWADARKSTONEEDGE.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 108]
	name=string:OCODFLLIGHTGROUNDGEROELL
	matGroup=enum:4
	color=color:71 63 43 255
	smoothAngle=float:60
	texture=string:OCODFLLIGHTGROUNDGEROELL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 109]
	name=string:OCIDFLSTONEFLOORLI
	matGroup=enum:2
	color=color:83 84 69 255
	smoothAngle=float:60
	texture=string:OCIDFLSTONEFLOORLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 110]
	name=string:OTFLTILE06A
	matGroup=enum:2
	color=color:90 80 60 255
	smoothAngle=float:60
	texture=string:OTFLTILE06A.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 111]
	name=string:OTFLTILE03
	matGroup=enum:2
	color=color:65 56 41 255
	smoothAngle=float:60
	texture=string:OTFLTILE03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 112]
	name=string:OWODPATRGRASSMIMOUNTAINCLOSE
	matGroup=enum:4
	color=color:89 81 61 255
	smoothAngle=float:60
	texture=string:OWODPATRGRASSMIMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 113]
	name=string:OTFLTILE05
	matGroup=enum:0
	color=color:90 77 58 255
	smoothAngle=float:60
	texture=string:OTFLTILE05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 114]
	name=string:OWODFLTRGRASSMILIPAI
	matGroup=enum:4
	color=color:96 86 65 255
	smoothAngle=float:60
	texture=string:OWODFLTRGRASSMILIPAI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 115]
	name=string:OWODPAIGRASSLI
	matGroup=enum:4
	color=color:83 76 60 255
	smoothAngle=float:60
	texture=string:OWODPAIGRASSLI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 116]
	name=string:OWODFLGRASSMI1
	matGroup=enum:0
	color=color:76 70 53 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMIMOUNTAINFARCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 117]
	name=string:OTFLTILE02
	matGroup=enum:2
	color=color:64 62 50 255
	smoothAngle=float:60
	texture=string:OTFLTILE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 118]
	name=string:OWODPATRGRASSMI
	matGroup=enum:4
	color=color:96 87 64 255
	smoothAngle=float:60
	texture=string:OWODPATRGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 119]
	name=string:ORKODFLFLOOR04
	matGroup=enum:0
	color=color:44 35 25 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 120]
	name=string:DTODFLSTONEFLOORMI
	matGroup=enum:2
	color=color:70 66 52 255
	smoothAngle=float:60
	texture=string:OCODFLSTONEFLOORMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:1
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 121]
	name=string:ORKODFLFLOOR16
	matGroup=enum:2
	color=color:60 56 46 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR16.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 122]
	name=string:ORKODTRFLOOR16FLOOR03
	matGroup=enum:2
	color=color:47 43 35 255
	smoothAngle=float:60
	texture=string:ORKODTRFLOOR16FLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 123]
	name=string:OWODFLGRASSDASTONE01
	matGroup=enum:4
	color=color:72 69 39 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSDASTONE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 124]
	name=string:OWODFLGRASSMI4
	matGroup=enum:4
	color=color:91 81 52 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 125]
	name=string:NCODFLGREY011
	matGroup=enum:0
	color=color:60 56 46 255
	smoothAngle=float:60
	texture=string:NCODFLGREY01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 126]
	name=string:OWODFLGRASSMI5
	matGroup=enum:4
	color=color:91 81 52 255
	smoothAngle=float:60
	texture=string:OWODFLGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 127]
	name=string:ORKODFLFLOOR11
	matGroup=enum:2
	color=color:42 36 34 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR11.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 128]
	name=string:ORKODFLTRFLOO1
	matGroup=enum:0
	color=color:52 45 35 255
	smoothAngle=float:60
	texture=string:ORKODFLTRFLOOR08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 129]
	name=string:FMCODFLGROUND
	matGroup=enum:2
	color=color:30 26 24 255
	smoothAngle=float:60
	texture=string:FMCODFLGROUND.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 130]
	name=string:FMCODFLGROUNDDOOR
	matGroup=enum:2
	color=color:37 32 27 255
	smoothAngle=float:60
	texture=string:FMCODFLGROUNDDOOR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 131]
	name=string:FMCIDFLSTRAW
	matGroup=enum:4
	color=color:101 89 71 255
	smoothAngle=float:60
	texture=string:FMCIDFLSTRAW.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 132]
	name=string:OTFLTILE02111
	matGroup=enum:0
	color=color:64 62 50 255
	smoothAngle=float:60
	texture=string:OTFLTILE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 133]
	name=string:OMWATRFLOORWALL12
	matGroup=enum:0
	color=color:71 71 67 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL12.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 134]
	name=string:BODPLAT
	matGroup=enum:0
	color=color:166 154 129 255
	smoothAngle=float:60
	texture=string:BODPLAT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 135]
	name=string:BODPLROT
	matGroup=enum:0
	color=color:178 149 130 255
	smoothAngle=float:60
	texture=string:BODPLROT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 136]
	name=string:FLOOR1
	matGroup=enum:0
	color=color:114 107 92 255
	smoothAngle=float:60
	texture=string:FLOOR1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 137]
	name=string:HOC3_CANYBENE_MID
	matGroup=enum:0
	color=color:103 78 59 255
	smoothAngle=float:60
	texture=string:HOC3_CANYBENE_MID.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 138]
	name=string:HOF1_DIRT
	matGroup=enum:0
	color=color:133 103 77 255
	smoothAngle=float:60
	texture=string:HOF1_DIRT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 139]
	name=string:HOW1_DIAG5
	matGroup=enum:0
	color=color:115 92 74 255
	smoothAngle=float:60
	texture=string:HOW1_DIAG5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 140]
	name=string:HOW1_DIAG_UNTEN3
	matGroup=enum:0
	color=color:100 79 63 255
	smoothAngle=float:60
	texture=string:HOW1_DIAG_UNTEN3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 141]
	name=string:HOW1_DIAG_UNTEN
	matGroup=enum:0
	color=color:106 85 68 255
	smoothAngle=float:60
	texture=string:HOW1_DIAG_UNTEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 142]
	name=string:KAIBARE
	matGroup=enum:0
	color=color:145 138 113 255
	smoothAngle=float:60
	texture=string:KAIBARE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 143]
	name=string:MODIHERB01
	matGroup=enum:0
	color=color:62 73 53 255
	smoothAngle=float:60
	texture=string:MODIHERB01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 144]
	name=string:MOSTORCTHRONE01
	matGroup=enum:0
	color=color:57 50 48 255
	smoothAngle=float:60
	texture=string:MOSTORCTHRONE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 145]
	name=string:MOSTORCTHRONE02
	matGroup=enum:0
	color=color:61 53 50 255
	smoothAngle=float:60
	texture=string:MOSTORCTHRONE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 146]
	name=string:NC_W_RPORTAL_128
	matGroup=enum:0
	color=color:59 56 47 255
	smoothAngle=float:60
	texture=string:NC_W_RPORTAL_128.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 147]
	name=string:NCODFLGREY01LI
	matGroup=enum:0
	color=color:73 70 62 255
	smoothAngle=float:60
	texture=string:NCODFLGREY01LI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 148]
	name=string:NCODFLLAKE01
	matGroup=enum:0
	color=color:53 47 24 255
	smoothAngle=float:60
	texture=string:NCODFLLAKE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 149]
	name=string:OCODPAGRASILI
	matGroup=enum:0
	color=color:99 89 61 255
	smoothAngle=float:60
	texture=string:OCODPAGRASILI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 150]
	name=string:ORKODFLFLOOR10
	matGroup=enum:0
	color=color:51 44 42 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR10.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 151]
	name=string:ORKODFLFLOOR14
	matGroup=enum:0
	color=color:85 74 69 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR14.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 152]
	name=string:ORKODFLFLOORWAY01
	matGroup=enum:0
	color=color:70 58 44 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOORWAY01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 153]
	name=string:ORKODFLFLOORWAY02
	matGroup=enum:0
	color=color:88 73 57 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOORWAY02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 154]
	name=string:ORKODFLFLOORWAY03
	matGroup=enum:0
	color=color:76 63 49 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOORWAY03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 155]
	name=string:ORKODFLFLOORWAY04
	matGroup=enum:0
	color=color:78 65 50 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOORWAY04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 156]
	name=string:ORKODFLFLOORWAY05
	matGroup=enum:0
	color=color:81 67 52 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOORWAY05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 157]
	name=string:ORKODFLFLOORWAY06
	matGroup=enum:0
	color=color:111 93 74 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOORWAY06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 158]
	name=string:ORKODFLTRFLOOR01
	matGroup=enum:0
	color=color:66 55 42 255
	smoothAngle=float:60
	texture=string:ORKODFLTRFLOOR01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 159]
	name=string:ORKODFLTRFLOORWALL01
	matGroup=enum:0
	color=color:50 41 33 255
	smoothAngle=float:60
	texture=string:ORKODFLTRFLOORWALL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 160]
	name=string:ORKODFLTRFLOORWALL22
	matGroup=enum:0
	color=color:49 42 33 255
	smoothAngle=float:60
	texture=string:ORKODFLTRFLOORWALL22.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 161]
	name=string:OTFLBROWN01
	matGroup=enum:0
	color=color:122 108 83 255
	smoothAngle=float:60
	texture=string:OTFLBROWN01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 162]
	name=string:OW_DIRTDECAL
	matGroup=enum:0
	color=color:133 132 131 255
	smoothAngle=float:60
	texture=string:OW_DIRTDECAL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 163]
	name=string:OWODFLTRGRASSLIFORRESTTERMITE
	matGroup=enum:0
	color=color:73 63 43 255
	smoothAngle=float:60
	texture=string:OWODFLTRGRASSLIFORRESTTERMITE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 164]
	name=string:OWODFLWALDTERMITE
	matGroup=enum:0
	color=color:89 77 57 255
	smoothAngle=float:60
	texture=string:OWODFLWALDTERMITE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 165]
	name=string:OWODPATRGRASSDA
	matGroup=enum:0
	color=color:85 79 51 255
	smoothAngle=float:60
	texture=string:OWODPATRGRASSDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 166]
	name=string:OWODTRGRASSDALIPAI
	matGroup=enum:0
	color=color:83 78 54 255
	smoothAngle=float:60
	texture=string:OWODTRGRASSDALIPAI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 167]
	name=string:OWODWALIGHTGROUND
	matGroup=enum:0
	color=color:72 63 40 255
	smoothAngle=float:60
	texture=string:OWODWALIGHTGROUND.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 168]
	name=string:SCHLAMM
	matGroup=enum:0
	color=color:114 101 93 255
	smoothAngle=float:60
	texture=string:SCHLAMM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 169]
	name=string:SIMPWALL
	matGroup=enum:0
	color=color:177 168 134 255
	smoothAngle=float:60
	texture=string:SIMPWALL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 170]
	name=string:WAY5
	matGroup=enum:0
	color=color:140 128 102 255
	smoothAngle=float:60
	texture=string:WAY5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 171]
	name=string:OTWADIRTFLOOR
	matGroup=enum:2
	color=color:52 45 30 255
	smoothAngle=float:60
	texture=string:OTWADIRTFLOOR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
