ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:56
user HornOx
END
objects 18       
END

[% zCMaterial 17408 0]
	name=string:OCODWATORHAUSKANTE
	matGroup=enum:2
	color=color:60 58 52 255
	smoothAngle=float:60
	texture=string:OCODWATORHAUSKANTE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:OCODWATORABSATZ
	matGroup=enum:2
	color=color:62 60 55 255
	smoothAngle=float:60
	texture=string:OCODWATORABSATZ.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:OCODWATORBOGEN
	matGroup=enum:2
	color=color:54 51 46 255
	smoothAngle=float:60
	texture=string:OCODWATORBOGEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:OCODWATORABSATZTRANDLOS
	matGroup=enum:2
	color=color:42 41 36 255
	smoothAngle=float:60
	texture=string:OCODWATORABSATZTRANDLOS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:OCODWATORGERADERANDLOS
	matGroup=enum:2
	color=color:37 35 30 255
	smoothAngle=float:60
	texture=string:OCODWATORGERADERANDLOS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:OCODWATORBOGENRANDLOS
	matGroup=enum:2
	color=color:39 38 33 255
	smoothAngle=float:60
	texture=string:OCODWATORBOGENRANDLOS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:OCODWATOR
	matGroup=enum:2
	color=color:62 59 53 255
	smoothAngle=float:60
	texture=string:OCODWATOR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:OCODWATORGERADE
	matGroup=enum:2
	color=color:59 56 50 255
	smoothAngle=float:60
	texture=string:OCODWATORGERADE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:OCODWATORRANDLOS
	matGroup=enum:2
	color=color:42 41 35 255
	smoothAngle=float:60
	texture=string:OCODWATORRANDLOS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:OCODWATORDOOR
	matGroup=enum:2
	color=color:39 38 33 255
	smoothAngle=float:60
	texture=string:OCODWATORDOOR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:OCODWATORBIGDOOR
	matGroup=enum:2
	color=color:32 33 26 255
	smoothAngle=float:60
	texture=string:OCODWATORBIGDOOR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:OCODWATORFENSTER
	matGroup=enum:2
	color=color:41 39 34 255
	smoothAngle=float:60
	texture=string:OCODWATORFENSTER.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:DTODWATORHAUSKANTE
	matGroup=enum:2
	color=color:60 58 52 255
	smoothAngle=float:60
	texture=string:OCODWATORHAUSKANTE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:1
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:DTODWATORRANDLOS
	matGroup=enum:2
	color=color:42 41 35 255
	smoothAngle=float:60
	texture=string:OCODWATORRANDLOS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:1
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:DTODWATORFENSTER
	matGroup=enum:2
	color=color:41 39 34 255
	smoothAngle=float:60
	texture=string:OCODWATORFENSTER.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:1
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:DTODWATORABSATZ
	matGroup=enum:2
	color=color:62 60 55 255
	smoothAngle=float:60
	texture=string:OCODWATORABSATZ.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:1
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:DTODWATORBOGEN
	matGroup=enum:2
	color=color:54 51 46 255
	smoothAngle=float:60
	texture=string:OCODWATORBOGEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:1
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:DTODWATOR
	matGroup=enum:2
	color=color:62 59 53 255
	smoothAngle=float:60
	texture=string:OCODWATOR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:1
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
