ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:56
user HornOx
END
objects 111      
END

[% zCMaterial 17408 0]
	name=string:OMWATRWALL04
	matGroup=enum:2
	color=color:62 59 47 255
	smoothAngle=float:60
	texture=string:OMWATRWALL04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:OMWAGREEN04
	matGroup=enum:2
	color=color:63 63 48 255
	smoothAngle=float:60
	texture=string:OMWAGREEN04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:OMWAGREEN11
	matGroup=enum:2
	color=color:73 71 56 255
	smoothAngle=float:60
	texture=string:OMWAGREEN11.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:OMWAGREEN10
	matGroup=enum:2
	color=color:71 69 53 255
	smoothAngle=float:60
	texture=string:OMWAGREEN10.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:OMWAGREEN09
	matGroup=enum:2
	color=color:63 62 50 255
	smoothAngle=float:60
	texture=string:OMWAGREEN09.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:OMWAGREEN03
	matGroup=enum:2
	color=color:63 62 47 255
	smoothAngle=float:60
	texture=string:OMWAGREEN03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:OMRECRAWLER05
	matGroup=enum:2
	color=color:132 112 80 255
	smoothAngle=float:60
	texture=string:OMRECRAWLER05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:OMRECRAWLER04
	matGroup=enum:2
	color=color:86 78 56 255
	smoothAngle=float:60
	texture=string:OMRECRAWLER04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:OMWAGREEN0111
	matGroup=enum:2
	color=color:59 64 53 255
	smoothAngle=float:60
	texture=string:OMWAGREEN01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:OMWAGREEN01
	matGroup=enum:2
	color=color:59 64 53 255
	smoothAngle=float:60
	texture=string:OMWAGREEN01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:OMRECRAWLER01
	matGroup=enum:0
	color=color:81 46 40 255
	smoothAngle=float:60
	texture=string:OMRECRAWLER01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:OMWAGREEN011
	matGroup=enum:2
	color=color:59 64 53 255
	smoothAngle=float:60
	texture=string:OMWAGREEN01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:OMRECRAWLER03
	matGroup=enum:0
	color=color:85 41 34 255
	smoothAngle=float:60
	texture=string:OMRECRAWLER03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:OMRETRCRAWLER02
	matGroup=enum:2
	color=color:66 59 48 255
	smoothAngle=float:60
	texture=string:OMRETRCRAWLER02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:OMRECRAWLER02
	matGroup=enum:0
	color=color:53 26 21 255
	smoothAngle=float:60
	texture=string:OMRECRAWLER02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:OMRECRAWLERLOCH
	matGroup=enum:0
	color=color:57 26 22 255
	smoothAngle=float:60
	texture=string:OMRECRAWLERLOCH.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:OMWABROWN07
	matGroup=enum:2
	color=color:64 58 45 255
	smoothAngle=float:60
	texture=string:OMWABROWN07.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:OMWAGREY04
	matGroup=enum:2
	color=color:66 69 68 255
	smoothAngle=float:60
	texture=string:OMWAGREY04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:OMWAGREEN06
	matGroup=enum:2
	color=color:60 61 50 255
	smoothAngle=float:60
	texture=string:OMWAGREEN06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:OMWAGREY03
	matGroup=enum:2
	color=color:87 86 75 255
	smoothAngle=float:60
	texture=string:OMWAGREY03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:OMWAGREY05
	matGroup=enum:2
	color=color:87 85 75 255
	smoothAngle=float:60
	texture=string:OMWAGREY05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:OMRETRCRAWLER01
	matGroup=enum:2
	color=color:65 53 43 255
	smoothAngle=float:60
	texture=string:OMRETRCRAWLER01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 22]
	name=string:OMWABROWN08
	matGroup=enum:2
	color=color:75 67 55 255
	smoothAngle=float:60
	texture=string:OMWABROWN08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 23]
	name=string:OMWAGREY02
	matGroup=enum:2
	color=color:73 70 57 255
	smoothAngle=float:60
	texture=string:OMWAGREY02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 24]
	name=string:OMWAGREEN05
	matGroup=enum:2
	color=color:70 70 57 255
	smoothAngle=float:60
	texture=string:OMWAGREEN05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 25]
	name=string:OMWAGREY01
	matGroup=enum:2
	color=color:107 107 95 255
	smoothAngle=float:60
	texture=string:OMWAGREY01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 26]
	name=string:OMWAGREEN08
	matGroup=enum:2
	color=color:67 66 54 255
	smoothAngle=float:60
	texture=string:OMWAGREEN08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 27]
	name=string:OMWAGREEN07
	matGroup=enum:2
	color=color:62 60 47 255
	smoothAngle=float:60
	texture=string:OMWAGREEN07.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 28]
	name=string:OMWABROWN05
	matGroup=enum:2
	color=color:57 54 35 255
	smoothAngle=float:60
	texture=string:OMWABROWN05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 29]
	name=string:OWODWAMOUNTAINFAR
	matGroup=enum:2
	color=color:52 53 54 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINFAR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 30]
	name=string:OWODWAMOUNTAINCLOSE
	matGroup=enum:2
	color=color:66 64 53 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 31]
	name=string:OWODWAGRASSDAMOUNTAINCLOSE
	matGroup=enum:2
	color=color:64 61 46 255
	smoothAngle=float:60
	texture=string:OWODWAGRASSDAMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 32]
	name=string:OWODWADARKSTONE
	matGroup=enum:2
	color=color:47 38 25 255
	smoothAngle=float:60
	texture=string:OWODWADARKSTONE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 33]
	name=string:OWODWATRMOUNTAINCLOSEMINE
	matGroup=enum:2
	color=color:58 56 41 255
	smoothAngle=float:60
	texture=string:OWODWATRMOUNTAINCLOSEMINE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 34]
	name=string:OWODWAMOUNTAI4
	matGroup=enum:2
	color=color:66 64 53 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 35]
	name=string:OMWABROWNGREEN01
	matGroup=enum:2
	color=color:57 55 41 255
	smoothAngle=float:60
	texture=string:OMWABROWNGREEN01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 36]
	name=string:OWODWAMOUNTAINCLOSEGRASSMI
	matGroup=enum:2
	color=color:79 74 56 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINCLOSEGRASSMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 37]
	name=string:OMWABROWN02
	matGroup=enum:2
	color=color:99 92 73 255
	smoothAngle=float:60
	texture=string:OMWABROWN02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 38]
	name=string:OWODWAMOUNTAINFARCLOSE
	matGroup=enum:2
	color=color:57 57 55 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINFARCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 39]
	name=string:OMWABROWN10
	matGroup=enum:4
	color=color:70 66 54 255
	smoothAngle=float:60
	texture=string:OMWABROWN10.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 40]
	name=string:OMWABROWN03
	matGroup=enum:2
	color=color:90 86 71 255
	smoothAngle=float:60
	texture=string:OMWABROWN03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 41]
	name=string:OWODWAMOUNTAI1
	matGroup=enum:2
	color=color:66 64 53 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 42]
	name=string:OMWAGREY011
	matGroup=enum:2
	color=color:107 107 95 255
	smoothAngle=float:60
	texture=string:OMWAGREY01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 43]
	name=string:OWODWAMOUNTAI3
	matGroup=enum:2
	color=color:66 64 53 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 44]
	name=string:OMWAGREEN02
	matGroup=enum:2
	color=color:65 65 48 255
	smoothAngle=float:60
	texture=string:OMWAGREEN02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 45]
	name=string:NCODWASTONEMUD
	matGroup=enum:2
	color=color:73 68 43 255
	smoothAngle=float:60
	texture=string:NCODWASTONEMUD.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 46]
	name=string:OWODWAMOUNTAI2
	matGroup=enum:2
	color=color:66 64 53 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 47]
	name=string:OMWAGREY06
	matGroup=enum:2
	color=color:49 55 50 255
	smoothAngle=float:60
	texture=string:OMWAGREY06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 48]
	name=string:OMWABROWN01
	matGroup=enum:2
	color=color:97 87 72 255
	smoothAngle=float:60
	texture=string:OMWABROWN01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 49]
	name=string:OMWABROWN04
	matGroup=enum:2
	color=color:57 56 43 255
	smoothAngle=float:60
	texture=string:OMWABROWN04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 50]
	name=string:ORKODFLFLOOR01
	matGroup=enum:2
	color=color:44 35 25 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 51]
	name=string:OMWABROWN12
	matGroup=enum:2
	color=color:65 59 44 255
	smoothAngle=float:60
	texture=string:OMWABROWN12.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 52]
	name=string:OWODWAMOUNTAI5
	matGroup=enum:2
	color=color:66 64 53 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 53]
	name=string:ORKODFLFLOOR02
	matGroup=enum:2
	color=color:35 31 26 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 54]
	name=string:OMWATRBROWN06MOUNTAINCLOSE
	matGroup=enum:2
	color=color:64 59 48 255
	smoothAngle=float:60
	texture=string:OMWATRBROWN06MOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 55]
	name=string:FMCWABROWN06
	matGroup=enum:2
	color=color:62 53 39 255
	smoothAngle=float:60
	texture=string:OMWABROWN06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 56]
	name=string:FMCODWATRGROUNDCLIFF
	matGroup=enum:2
	color=color:58 50 38 255
	smoothAngle=float:60
	texture=string:FMCODWATRGROUNDCLIFF.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 57]
	name=string:OWODWAMOUNTAI11
	matGroup=enum:2
	color=color:66 64 53 255
	smoothAngle=float:60
	texture=string:OWODWAMOUNTAINCLOSE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 58]
	name=string:OMWAGREY08
	matGroup=enum:2
	color=color:86 83 70 255
	smoothAngle=float:60
	texture=string:OMWAGREY08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 59]
	name=string:OT_WA_FLOORFORSPIKES
	matGroup=enum:2
	color=color:60 56 46 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR16.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 60]
	name=string:OMTRGREEN01GRAY08
	matGroup=enum:2
	color=color:74 75 63 255
	smoothAngle=float:60
	texture=string:OMTRGREEN01GRAY08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 61]
	name=string:OTWADIRT01
	matGroup=enum:2
	color=color:54 48 31 255
	smoothAngle=float:60
	texture=string:OTWADIRT01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 62]
	name=string:OTWAGOLD
	matGroup=enum:2
	color=color:59 41 18 255
	smoothAngle=float:60
	texture=string:OTWAGOLD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 63]
	name=string:OTWASITALLIPLAIN
	matGroup=enum:2
	color=color:114 105 76 255
	smoothAngle=float:60
	texture=string:OTWASITALLIPLAIN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 64]
	name=string:OMWATRFLOORWALL14
	matGroup=enum:2
	color=color:68 64 56 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL14.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 65]
	name=string:OTFLTILE08
	matGroup=enum:2
	color=color:60 52 38 255
	smoothAngle=float:60
	texture=string:OTFLTILE08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 66]
	name=string:OTFLDIRT01
	matGroup=enum:2
	color=color:48 45 33 255
	smoothAngle=float:60
	texture=string:OTFLDIRT01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 67]
	name=string:OMWAGREY081
	matGroup=enum:2
	color=color:86 83 70 255
	smoothAngle=float:60
	texture=string:OMWAGREY08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 68]
	name=string:OTTRSITAL2
	matGroup=enum:2
	color=color:91 83 58 255
	smoothAngle=float:60
	texture=string:OTTRSITAL2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 69]
	name=string:SAEULENMATERIAL_ORCTEMPLE_01
	matGroup=enum:2
	color=color:60 56 46 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR16.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 70]
	name=string:NEWFELS2
	matGroup=enum:2
	color=color:161 152 123 255
	smoothAngle=float:60
	texture=string:NEWFELS2.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 71]
	name=string:X_NEWFELS4
	matGroup=enum:2
	color=color:137 130 109 255
	smoothAngle=float:60
	texture=string:NEWFELS4.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 72]
	name=string:HOW3_CANYON_MID
	matGroup=enum:2
	color=color:86 68 54 255
	smoothAngle=float:60
	texture=string:HOW3_CANYON_MID4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 73]
	name=string:NEWFELS4
	matGroup=enum:2
	color=color:137 130 109 255
	smoothAngle=float:60
	texture=string:NEWFELS4.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 74]
	name=string:SCHALEA
	matGroup=enum:2
	color=color:41 36 29 255
	smoothAngle=float:60
	texture=string:COPPER.TGA
	texScale=string:64 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 75]
	name=string:ERZ
	matGroup=enum:0
	color=color:68 58 60 255
	smoothAngle=float:60
	texture=string:ERZ.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 76]
	name=string:HERD
	matGroup=enum:0
	color=color:60 51 49 255
	smoothAngle=float:60
	texture=string:HERD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 77]
	name=string:MOSTMARMOR01
	matGroup=enum:0
	color=color:54 58 57 255
	smoothAngle=float:60
	texture=string:MOSTMARMOR01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 78]
	name=string:MOSTOREHEAP_01
	matGroup=enum:0
	color=color:52 47 67 255
	smoothAngle=float:60
	texture=string:MOSTOREHEAP_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 79]
	name=string:MOSTOREHEAP_02
	matGroup=enum:0
	color=color:47 41 97 255
	smoothAngle=float:60
	texture=string:MOSTOREHEAP_02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 80]
	name=string:MOSTOREHEAP_03
	matGroup=enum:0
	color=color:85 53 41 255
	smoothAngle=float:60
	texture=string:MOSTOREHEAP_03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 81]
	name=string:MOSTOREHEAP_04
	matGroup=enum:0
	color=color:70 53 44 255
	smoothAngle=float:60
	texture=string:MOSTOREHEAP_04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 82]
	name=string:MOWOBARK01
	matGroup=enum:0
	color=color:55 53 49 255
	smoothAngle=float:60
	texture=string:MOWOBARK01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 83]
	name=string:NCODWADARKSTONE02
	matGroup=enum:0
	color=color:75 72 63 255
	smoothAngle=float:60
	texture=string:NCODWADARKSTONE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 84]
	name=string:NEWFELS1
	matGroup=enum:0
	color=color:147 133 113 255
	smoothAngle=float:60
	texture=string:NEWFELS1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 85]
	name=string:NEWFELS3
	matGroup=enum:0
	color=color:165 154 114 255
	smoothAngle=float:60
	texture=string:NEWFELS3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 86]
	name=string:OMWABROWN09
	matGroup=enum:0
	color=color:98 91 73 255
	smoothAngle=float:60
	texture=string:OMWABROWN09.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 87]
	name=string:OMWABROWN11
	matGroup=enum:0
	color=color:76 67 52 255
	smoothAngle=float:60
	texture=string:OMWABROWN11.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 88]
	name=string:OMWADIRT01 KOPIE
	matGroup=enum:0
	color=color:54 50 35 255
	smoothAngle=float:60
	texture=string:OMWADIRT01 KOPIE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 89]
	name=string:OMWAGREEN01A
	matGroup=enum:0
	color=color:62 62 50 255
	smoothAngle=float:60
	texture=string:OMWAGREEN01A.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 90]
	name=string:OMWAGREENGREY01
	matGroup=enum:0
	color=color:68 68 58 255
	smoothAngle=float:60
	texture=string:OMWAGREENGREY01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 91]
	name=string:OMWAGREY07
	matGroup=enum:0
	color=color:69 70 59 255
	smoothAngle=float:60
	texture=string:OMWAGREY07.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 92]
	name=string:OMWAGREY09
	matGroup=enum:0
	color=color:69 69 57 255
	smoothAngle=float:60
	texture=string:OMWAGREY09.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 93]
	name=string:OMWATRFLOORWALL08
	matGroup=enum:0
	color=color:67 68 62 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 94]
	name=string:OMWATRFLOORWALL13
	matGroup=enum:0
	color=color:66 65 52 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL13.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 95]
	name=string:OMWATRFLOORWALL15
	matGroup=enum:0
	color=color:68 69 59 255
	smoothAngle=float:60
	texture=string:OMWATRFLOORWALL15.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 96]
	name=string:OMWATRWALL05
	matGroup=enum:0
	color=color:52 52 39 255
	smoothAngle=float:60
	texture=string:OMWATRWALL05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 97]
	name=string:OMWATRWALL06
	matGroup=enum:0
	color=color:77 71 55 255
	smoothAngle=float:60
	texture=string:OMWATRWALL06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 98]
	name=string:OMWATRWALL07
	matGroup=enum:0
	color=color:72 71 55 255
	smoothAngle=float:60
	texture=string:OMWATRWALL07.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 99]
	name=string:OMWATRWALL08
	matGroup=enum:0
	color=color:66 63 50 255
	smoothAngle=float:60
	texture=string:OMWATRWALL08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 100]
	name=string:ORKODFLFLOOR09
	matGroup=enum:0
	color=color:41 36 29 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOOR09.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 101]
	name=string:ORKODFLTRFLOOR07
	matGroup=enum:0
	color=color:60 50 42 255
	smoothAngle=float:60
	texture=string:ORKODFLTRFLOOR07.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 102]
	name=string:ORKODTRWALL01FLOOR03
	matGroup=enum:0
	color=color:49 42 35 255
	smoothAngle=float:60
	texture=string:ORKODTRWALL01FLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 103]
	name=string:ORKODTRWALL02FLOOR03
	matGroup=enum:0
	color=color:48 43 38 255
	smoothAngle=float:60
	texture=string:ORKODTRWALL02FLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 104]
	name=string:ORKODTRWALL02FLOOR03HO
	matGroup=enum:0
	color=color:44 40 35 255
	smoothAngle=float:60
	texture=string:ORKODTRWALL02FLOOR03HO.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 105]
	name=string:ORKODTRWALL02WALL01
	matGroup=enum:0
	color=color:60 55 50 255
	smoothAngle=float:60
	texture=string:ORKODTRWALL02WALL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 106]
	name=string:ORKODTRWALL04FLOOR03
	matGroup=enum:0
	color=color:44 38 33 255
	smoothAngle=float:60
	texture=string:ORKODTRWALL04FLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 107]
	name=string:ORKODTRWALL10FLOOR03
	matGroup=enum:0
	color=color:45 42 36 255
	smoothAngle=float:60
	texture=string:ORKODTRWALL10FLOOR03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 108]
	name=string:ORKODTRWALL10WALL02
	matGroup=enum:0
	color=color:61 55 46 255
	smoothAngle=float:60
	texture=string:ORKODTRWALL10WALL02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 109]
	name=string:ORKODWALL03
	matGroup=enum:0
	color=color:52 44 36 255
	smoothAngle=float:60
	texture=string:ORKODWALL03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 110]
	name=string:ORKODWALL04
	matGroup=enum:0
	color=color:57 48 43 255
	smoothAngle=float:60
	texture=string:ORKODWALL04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
