ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:56
user HornOx
END
objects 96       
END

[% zCMaterial 17408 0]
	name=string:ORKODREFLOOR01
	matGroup=enum:2
	color=color:42 37 34 255
	smoothAngle=float:60
	texture=string:ORKODREFLOOR01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:PCODWATEMPLESTAIRS_01
	matGroup=enum:2
	color=color:35 30 21 255
	smoothAngle=float:60
	texture=string:PCODWATEMPLESTAIRS_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:1 1 
[]
[% zCMaterial 17408 2]
	name=string:FMCIDWAWALL
	matGroup=enum:3
	color=color:36 26 15 255
	smoothAngle=float:60
	texture=string:FMCIDWAWALL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:OCODWAPUTZMITBALKEN
	matGroup=enum:2
	color=color:87 81 66 255
	smoothAngle=float:60
	texture=string:OCODWAPUTZMITBALKEN.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:PCIDWAWAND01
	matGroup=enum:0
	color=color:56 54 28 255
	smoothAngle=float:60
	texture=string:PCIDWAWAND01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:TEMPELSTAIRS
	matGroup=enum:0
	color=color:35 30 21 255
	smoothAngle=float:60
	texture=string:PCODWATEMPLESTAIRS_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:PCIDWAFRONTPANEL01
	matGroup=enum:0
	color=color:30 27 17 255
	smoothAngle=float:60
	texture=string:PCIDWAFRONTPANEL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:MOWOWOODS01
	matGroup=enum:0
	color=color:51 37 29 255
	smoothAngle=float:60
	texture=string:MOWOWOODS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:PCODWAWAND01
	matGroup=enum:3
	color=color:53 45 27 255
	smoothAngle=float:60
	texture=string:PCODWAWAND01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:PCODWAFRONTPANEL01
	matGroup=enum:3
	color=color:52 49 28 255
	smoothAngle=float:60
	texture=string:PCODWAFRONTPANEL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:PCODWAWACHPOSTEN01
	matGroup=enum:3
	color=color:48 43 29 255
	smoothAngle=float:60
	texture=string:PCODWAWACHPOSTEN01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:PSI_ABHAENGE_TUCH
	matGroup=enum:0
	color=color:45 35 22 255
	smoothAngle=float:60
	texture=string:MODILEATHERSLEEVE01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:PSICAMP_TEMPEL_SCHALEN_FEUER
	matGroup=enum:0
	color=color:73 65 52 255
	smoothAngle=float:60
	texture=string:MOMESMELT01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:PSI_TEMPLE_STAIRS_01
	matGroup=enum:0
	color=color:35 30 21 255
	smoothAngle=float:60
	texture=string:PCODWATEMPLESTAIRS_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:PSI_TEMPLE_WOODENPLANKS
	matGroup=enum:0
	color=color:74 62 50 255
	smoothAngle=float:60
	texture=string:MOWOPLANKS06.TGA
	texScale=string:128 32
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:PCIDWASIDEPANEL01
	matGroup=enum:3
	color=color:52 49 33 255
	smoothAngle=float:60
	texture=string:PCIDWASIDEPANEL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:ROPEWAY_MAT7
	matGroup=enum:0
	color=color:53 40 33 255
	smoothAngle=float:60
	texture=string:MOWOWHEEL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:ROPEWAY_MAT3
	matGroup=enum:0
	color=color:80 61 41 255
	smoothAngle=float:60
	texture=string:MOWOWOODS02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:ROPEWAY_MAT2
	matGroup=enum:0
	color=color:51 37 29 255
	smoothAngle=float:60
	texture=string:MOWOWOODS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:ROPEWAY_MAT9
	matGroup=enum:0
	color=color:91 80 48 255
	smoothAngle=float:60
	texture=string:MODIBACKPACK02.TGA
	texScale=string:64 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:OCODWARINGTOPLI
	matGroup=enum:3
	color=color:49 40 26 255
	smoothAngle=float:60
	texture=string:OCODWARINGTOPLI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:OCODWARINGTOPMI
	matGroup=enum:3
	color=color:46 38 24 255
	smoothAngle=float:60
	texture=string:OCODWARINGTOPMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 22]
	name=string:OCODWARINGAI
	matGroup=enum:3
	color=color:53 48 37 255
	smoothAngle=float:60
	texture=string:OCODWARINGAI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 23]
	name=string:OCODWARINGDA
	matGroup=enum:3
	color=color:55 50 39 255
	smoothAngle=float:60
	texture=string:OCODWARINGDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 24]
	name=string:NCODWAMATTE
	matGroup=enum:3
	color=color:44 40 32 255
	smoothAngle=float:60
	texture=string:NCODWAMATTE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 25]
	name=string:OCODWATEXTILALPHA
	matGroup=enum:0
	color=color:49 43 33 255
	smoothAngle=float:60
	texture=string:OCODWATEXTILALPHA.TGA
	texScale=string:128 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 26]
	name=string:OCODWA4RINGS
	matGroup=enum:3
	color=color:71 54 39 255
	smoothAngle=float:60
	texture=string:OCODWA4RINGS.TGA
	texScale=string:64 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 27]
	name=string:OCODWAZIEGEL
	matGroup=enum:3
	color=color:76 37 26 255
	smoothAngle=float:60
	texture=string:OCODWAZIEGEL.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 28]
	name=string:OC_OLDSAWHOUSE_V1_4
	matGroup=enum:0
	color=color:71 54 39 255
	smoothAngle=float:60
	texture=string:MOWORINGS01.TGA
	texScale=string:64 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 29]
	name=string:OC_OLDSAWHOUSE_V1_2
	matGroup=enum:0
	color=color:31 22 20 255
	smoothAngle=float:60
	texture=string:MOWOBARREL01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 30]
	name=string:OCODWA4RINGS1
	matGroup=enum:0
	color=color:71 54 39 255
	smoothAngle=float:60
	texture=string:OCODWA4RINGS.TGA
	texScale=string:64 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 31]
	name=string:NCODWACHAOSWOODLA
	matGroup=enum:3
	color=color:54 47 32 255
	smoothAngle=float:60
	texture=string:NCODWACHAOSWOODLA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 32]
	name=string:OCODFLGATELI
	matGroup=enum:1
	color=color:23 23 17 255
	smoothAngle=float:60
	texture=string:OCODFLGATELI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 33]
	name=string:OCODFLGATEMI
	matGroup=enum:1
	color=color:30 28 27 255
	smoothAngle=float:60
	texture=string:OCODFLGATEMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 34]
	name=string:OCIDWASTONEFOREXIT
	matGroup=enum:2
	color=color:51 24 18 255
	smoothAngle=float:60
	texture=string:OCIDWASTONEFOREXIT.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 35]
	name=string:ORCTEP_BIGSTAIRS_01
	matGroup=enum:0
	color=color:35 30 21 255
	smoothAngle=float:60
	texture=string:PCODWATEMPLESTAIRS_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 36]
	name=string:OTFL_SPIKEHOLES_IN_FLOOR_01
	matGroup=enum:0
	color=color:41 29 20 255
	smoothAngle=float:60
	texture=string:OTFLSPIKEHOLES.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 37]
	name=string:OTFLSPIKESINHOLES_TILEBAR
	matGroup=enum:0
	color=color:36 22 15 255
	smoothAngle=float:60
	texture=string:OTFLSPIKEHOLES_TILE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 38]
	name=string:OC_W_INSIDEPUTZ_K
	matGroup=enum:0
	color=color:87 81 66 255
	smoothAngle=float:60
	texture=string:OCODWAPUTZMITBALKEN.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 39]
	name=string:ITW_WOOD1
	matGroup=enum:0
	color=color:79 82 90 255
	smoothAngle=float:60
	texture=string:DACH.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 40]
	name=string:ATW1_PUTZONLY
	matGroup=enum:0
	color=color:182 162 136 255
	smoothAngle=float:60
	texture=string:ATW1_PUTZONLY.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 41]
	name=string:SQADPLAT
	matGroup=enum:0
	color=color:174 147 109 255
	smoothAngle=float:60
	texture=string:SQARBOD.TGA
	texScale=string:64 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 42]
	name=string:OCODWADUNGEONDOOR
	matGroup=enum:2
	color=color:24 25 19 255
	smoothAngle=float:60
	texture=string:OCODWADUNGEONDOOR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 43]
	name=string:OCIDWASTONEINSIDEDOORMI
	matGroup=enum:2
	color=color:44 44 34 255
	smoothAngle=float:60
	texture=string:OCIDWASTONEINSIDEDOORMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 44]
	name=string:OCODWASIFFGRABEN
	matGroup=enum:2
	color=color:55 57 41 255
	smoothAngle=float:60
	texture=string:OCODWASIFFGRABEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 45]
	name=string:OCODWASMALLSTONES01
	matGroup=enum:2
	color=color:57 58 42 255
	smoothAngle=float:45
	texture=string:OCODWASMALLSTONES01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 46]
	name=string:OCODWASIFFGRA1
	matGroup=enum:2
	color=color:55 57 41 255
	smoothAngle=float:60
	texture=string:OCODWASIFFGRABEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 47]
	name=string:OCODWASMALLSTONELI
	matGroup=enum:2
	color=color:56 57 42 255
	smoothAngle=float:60
	texture=string:OCODWASMALLSTONELI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 48]
	name=string:OCODWABIGSTONES
	matGroup=enum:2
	color=color:56 57 42 255
	smoothAngle=float:60
	texture=string:OCODWABIGSTONES.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 49]
	name=string:OC_OLDSAWHOUSE_V1_1
	matGroup=enum:2
	color=color:38 42 33 255
	smoothAngle=float:60
	texture=string:OCODWADARKDIRTSTONES.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 50]
	name=string:OCODWADARKDIRTSTONES
	matGroup=enum:2
	color=color:38 42 33 255
	smoothAngle=float:60
	texture=string:OCODWADARKDIRTSTONES.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 51]
	name=string:OCODWASMALLSTONEBROKENLI
	matGroup=enum:2
	color=color:58 59 43 255
	smoothAngle=float:60
	texture=string:OCODWASMALLSTONEBROKENLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 52]
	name=string:OCODWASMALLSTONEBROKENMI
	matGroup=enum:2
	color=color:59 60 44 255
	smoothAngle=float:60
	texture=string:OCODWASMALLSTONEBROKENMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 53]
	name=string:OCIDWASTONEINSIDE
	matGroup=enum:2
	color=color:56 57 42 255
	smoothAngle=float:60
	texture=string:OCIDWASTONEINSIDE.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 54]
	name=string:OCODWASMALLSTONEMI
	matGroup=enum:2
	color=color:60 61 45 255
	smoothAngle=float:60
	texture=string:OCODWASMALLSTONEMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 55]
	name=string:OC_W_SMALLSTONEBROKEN_K
	matGroup=enum:2
	color=color:58 59 43 255
	smoothAngle=float:60
	texture=string:OCODWASMALLSTONEBROKENLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 56]
	name=string:OC_W_ISTONE
	matGroup=enum:2
	color=color:59 60 44 255
	smoothAngle=float:60
	texture=string:OCODWASMALLSTONEBROKENMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 57]
	name=string:AUSFLUSS
	matGroup=enum:0
	color=color:131 126 95 255
	smoothAngle=float:60
	texture=string:AUSFLUSS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 58]
	name=string:DOOR33A5
	matGroup=enum:0
	color=color:159 149 123 255
	smoothAngle=float:60
	texture=string:DOOR33A5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 59]
	name=string:DOOR33D
	matGroup=enum:0
	color=color:165 155 127 255
	smoothAngle=float:60
	texture=string:DOOR33D.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 60]
	name=string:DOORB-A5
	matGroup=enum:0
	color=color:159 149 122 255
	smoothAngle=float:60
	texture=string:DOORB-A5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 61]
	name=string:KAIHOLE3
	matGroup=enum:0
	color=color:132 128 104 255
	smoothAngle=float:60
	texture=string:KAIHOLE3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 62]
	name=string:KAISEGM
	matGroup=enum:0
	color=color:135 130 105 255
	smoothAngle=float:60
	texture=string:KAISEGM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 63]
	name=string:KAIWALL3
	matGroup=enum:0
	color=color:138 132 109 255
	smoothAngle=float:60
	texture=string:KAIWALL3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 64]
	name=string:MAURGELB
	matGroup=enum:0
	color=color:171 162 130 255
	smoothAngle=float:60
	texture=string:MAURGELB.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 65]
	name=string:MODICURTAIN01
	matGroup=enum:0
	color=color:89 81 58 255
	smoothAngle=float:60
	texture=string:MODICURTAIN01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 66]
	name=string:MOSTORCTHRONE03
	matGroup=enum:0
	color=color:111 97 83 255
	smoothAngle=float:60
	texture=string:MOSTORCTHRONE03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 67]
	name=string:MOSTSTEP01
	matGroup=enum:0
	color=color:76 70 57 255
	smoothAngle=float:60
	texture=string:MOSTSTEP01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 68]
	name=string:MOSTSTEP02
	matGroup=enum:0
	color=color:72 66 54 255
	smoothAngle=float:60
	texture=string:MOSTSTEP02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 69]
	name=string:MOSTSTONEROPE01
	matGroup=enum:0
	color=color:70 67 55 255
	smoothAngle=float:60
	texture=string:MOSTSTONEROPE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 70]
	name=string:MOSTSTONEROPE02
	matGroup=enum:0
	color=color:63 56 52 255
	smoothAngle=float:60
	texture=string:MOSTSTONEROPE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 71]
	name=string:MOSTSTONES01
	matGroup=enum:0
	color=color:64 65 50 255
	smoothAngle=float:60
	texture=string:MOSTSTONES01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 72]
	name=string:MOSTWALL01
	matGroup=enum:0
	color=color:76 71 58 255
	smoothAngle=float:60
	texture=string:MOSTWALL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 73]
	name=string:MOWOBEDS02
	matGroup=enum:0
	color=color:100 85 60 255
	smoothAngle=float:60
	texture=string:MOWOBEDS02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 74]
	name=string:OC_W_FARDOOR_128
	matGroup=enum:0
	color=color:30 28 23 255
	smoothAngle=float:60
	texture=string:OC_W_FARDOOR_128.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 75]
	name=string:OC_W_HUETTENTOR_128
	matGroup=enum:0
	color=color:39 34 24 255
	smoothAngle=float:60
	texture=string:OC_W_HUETTENTOR_128.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 76]
	name=string:OCIDWASTONEINSIDEDOORLI
	matGroup=enum:0
	color=color:41 41 31 255
	smoothAngle=float:60
	texture=string:OCIDWASTONEINSIDEDOORLI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 77]
	name=string:OCIDWASTONEINSIDEWINDOWS
	matGroup=enum:0
	color=color:47 48 36 255
	smoothAngle=float:60
	texture=string:OCIDWASTONEINSIDEWINDOWS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 78]
	name=string:OCODWAPORTAL
	matGroup=enum:0
	color=color:29 27 20 255
	smoothAngle=float:60
	texture=string:OCODWAPORTAL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 79]
	name=string:ORKODFLTRFLOOR12
	matGroup=enum:0
	color=color:52 44 35 255
	smoothAngle=float:60
	texture=string:ORKODFLTRFLOOR12.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 80]
	name=string:ORNAHALB
	matGroup=enum:0
	color=color:170 160 128 255
	smoothAngle=float:60
	texture=string:ORNAHALB.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 81]
	name=string:ORNAWALL
	matGroup=enum:0
	color=color:155 143 114 255
	smoothAngle=float:60
	texture=string:ORNAWALL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 82]
	name=string:OTWASTONELI08
	matGroup=enum:0
	color=color:118 108 82 255
	smoothAngle=float:60
	texture=string:OTWASTONELI08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 83]
	name=string:PLANSIFF
	matGroup=enum:0
	color=color:164 153 122 255
	smoothAngle=float:60
	texture=string:PLANSIFF.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 84]
	name=string:PLANWAND
	matGroup=enum:0
	color=color:175 167 133 255
	smoothAngle=float:60
	texture=string:PLANWAND.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 85]
	name=string:PORTAL4
	matGroup=enum:0
	color=color:174 161 130 255
	smoothAngle=float:60
	texture=string:PORTAL4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 86]
	name=string:PORTSAUL
	matGroup=enum:0
	color=color:181 170 139 255
	smoothAngle=float:60
	texture=string:PORTSAUL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 87]
	name=string:PORTWAL4
	matGroup=enum:0
	color=color:173 160 129 255
	smoothAngle=float:60
	texture=string:PORTWAL4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 88]
	name=string:SYMWALL5
	matGroup=enum:0
	color=color:152 138 110 255
	smoothAngle=float:60
	texture=string:SYMWALL5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 89]
	name=string:SYMWAND4
	matGroup=enum:0
	color=color:163 151 124 255
	smoothAngle=float:60
	texture=string:SYMWAND4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 90]
	name=string:SYMWAND5
	matGroup=enum:0
	color=color:155 142 115 255
	smoothAngle=float:60
	texture=string:SYMWAND5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 91]
	name=string:TREPBOD
	matGroup=enum:0
	color=color:111 83 65 255
	smoothAngle=float:60
	texture=string:TREPBOD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 92]
	name=string:TREPKANT
	matGroup=enum:0
	color=color:133 108 88 255
	smoothAngle=float:60
	texture=string:TREPKANT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 93]
	name=string:WAND5
	matGroup=enum:0
	color=color:159 144 115 255
	smoothAngle=float:60
	texture=string:WAND5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 94]
	name=string:WANDHOCH
	matGroup=enum:0
	color=color:171 160 128 255
	smoothAngle=float:60
	texture=string:WANDHOCH.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 95]
	name=string:AL_D_CELLAR
	matGroup=enum:0
	color=color:75 72 65 255
	smoothAngle=float:60
	texture=string:AL_D_CELLAR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
