ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:56
user HornOx
END
objects 15       
END

[% zCMaterial 17408 0]
	name=string:ATDOOR1
	matGroup=enum:2
	color=color:120 108 92 255
	smoothAngle=float:60
	texture=string:ATDOOR1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:ATF1_MIDBOD
	matGroup=enum:2
	color=color:189 170 145 255
	smoothAngle=float:60
	texture=string:ATF1_MIDBOD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:ATPORTAL1_OBEN2
	matGroup=enum:2
	color=color:130 116 98 255
	smoothAngle=float:60
	texture=string:ATPORTAL1_OBEN2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:ATSAUL1_MIT
	matGroup=enum:2
	color=color:175 156 131 255
	smoothAngle=float:60
	texture=string:ATSAUL1_MIT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:ATSAUL1_TOP
	matGroup=enum:2
	color=color:158 142 120 255
	smoothAngle=float:60
	texture=string:ATSAUL1_TOP.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:ATSAUL1_UNT
	matGroup=enum:2
	color=color:173 155 130 255
	smoothAngle=float:60
	texture=string:ATSAUL1_UNT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:ATW1_DECKABS
	matGroup=enum:2
	color=color:137 121 104 255
	smoothAngle=float:60
	texture=string:ATW1_DECKABS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:ATW1_FIGMITTE_UNTEN
	matGroup=enum:2
	color=color:133 120 101 255
	smoothAngle=float:60
	texture=string:ATW1_FIGMITTE_UNTEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:ATW1_NOPUTZ
	matGroup=enum:2
	color=color:147 130 112 255
	smoothAngle=float:60
	texture=string:ATW1_NOPUTZ.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:ATW1_W2KANTE_RECHTS_MID
	matGroup=enum:2
	color=color:152 135 115 255
	smoothAngle=float:60
	texture=string:ATW1_W2KANTE_RECHTS_MID.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:ATW1_W2KANTE_RECHTS
	matGroup=enum:2
	color=color:152 136 116 255
	smoothAngle=float:60
	texture=string:ATW1_W2KANTE_RECHTS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:ATW1_W2RANDR_UNTEN
	matGroup=enum:2
	color=color:151 135 115 255
	smoothAngle=float:60
	texture=string:ATW1_W2RANDR_UNTEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:ATW1_X_FIGMITTE_MAUER
	matGroup=enum:2
	color=color:140 125 107 255
	smoothAngle=float:60
	texture=string:ATW1_X_FIGMITTE_MAUER.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:ATW2_MOOSKANT
	matGroup=enum:2
	color=color:157 140 118 255
	smoothAngle=float:60
	texture=string:ATW2_MOOSKANT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:ATW2_SOCKEL_UNTEN
	matGroup=enum:2
	color=color:166 150 125 255
	smoothAngle=float:60
	texture=string:ATW2_SOCKEL_UNTEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
