ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:56
user HornOx
END
objects 11       
END

[% zCMaterial 17408 0]
	name=string:BLUESKY
	matGroup=enum:0
	color=color:149 123 99 255
	smoothAngle=float:60
	texture=string:BLUESKY.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:NIGHTCLOUDS
	matGroup=enum:0
	color=color:27 27 58 255
	smoothAngle=float:60
	texture=string:NIGHTCLOUDS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:RAINCLOUDS
	matGroup=enum:0
	color=color:41 48 52 255
	smoothAngle=float:60
	texture=string:RAINCLOUDS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:SCREEN_ORCVISION
	matGroup=enum:0
	color=color:157 213 231 255
	smoothAngle=float:60
	texture=string:SCREEN_ORCVISION.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:SKYRAINCLOUDS
	matGroup=enum:0
	color=color:41 48 52 255
	smoothAngle=float:60
	texture=string:SKYRAINCLOUDS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:SUNCLOUDS
	matGroup=enum:0
	color=color:153 128 103 255
	smoothAngle=float:60
	texture=string:SUNCLOUDS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:UNREALCLOUD1
	matGroup=enum:0
	color=color:91 120 144 255
	smoothAngle=float:60
	texture=string:UNREALCLOUD1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:SKYDAY_LAYER0_A0
	matGroup=enum:0
	color=color:255 255 255 255
	smoothAngle=float:60
	texture=string:SKYDAY_LAYER0_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:SKYDAY_LAYER1_A0
	matGroup=enum:0
	color=color:255 255 255 255
	smoothAngle=float:60
	texture=string:SKYDAY_LAYER1_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:SKYNIGHT_LAYER0_A0
	matGroup=enum:0
	color=color:2 12 24 255
	smoothAngle=float:60
	texture=string:SKYNIGHT_LAYER0_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:SKYNIGHT_LAYER1_A0
	matGroup=enum:0
	color=color:49 49 77 255
	smoothAngle=float:60
	texture=string:SKYNIGHT_LAYER1_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
