ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:57
user HornOx
END
objects 66       
END

[% zCMaterial 17408 0]
	name=string:OLD_PSI_RICEHUT_05
	matGroup=enum:3
	color=color:70 68 52 255
	smoothAngle=float:60
	texture=string:MOWOPLANKS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:OCODWAWOODDA
	matGroup=enum:3
	color=color:55 49 29 255
	smoothAngle=float:60
	texture=string:OCODWAWOODDA.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:OWODWAOLDWOOD
	matGroup=enum:3
	color=color:62 57 37 255
	smoothAngle=float:60
	texture=string:OWODWAOLDWOOD.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:OWODWAOLDWOOD01
	matGroup=enum:3
	color=color:43 36 23 255
	smoothAngle=float:60
	texture=string:OWODWAOLDWOOD01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:PCODWASIDEPANEL01
	matGroup=enum:3
	color=color:55 51 30 255
	smoothAngle=float:60
	texture=string:PCODWASIDEPANEL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:PSI_STEGESIDE_01
	matGroup=enum:3
	color=color:50 48 28 255
	smoothAngle=float:60
	texture=string:PCODWASTEGESIDE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:PSI_BRIDGE_PLANKS
	matGroup=enum:3
	color=color:60 57 32 255
	smoothAngle=float:60
	texture=string:PCODFLSTEG01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:PCODFLSTEG01
	matGroup=enum:3
	color=color:60 57 32 255
	smoothAngle=float:60
	texture=string:PCODFLSTEG01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:PCODWASTEGESIDE01
	matGroup=enum:3
	color=color:50 48 28 255
	smoothAngle=float:60
	texture=string:PCODWASTEGESIDE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:PCODWASTEGESIDE02
	matGroup=enum:3
	color=color:55 55 30 255
	smoothAngle=float:60
	texture=string:PCODWASTEGESIDE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:MOWOPLANKS01
	matGroup=enum:3
	color=color:70 68 52 255
	smoothAngle=float:60
	texture=string:MOWOPLANKS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:OWODFLBRETTER
	matGroup=enum:3
	color=color:58 55 39 255
	smoothAngle=float:60
	texture=string:OWODFLBRETTER.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:OCODWATORRANDLOSHAUSKANTE
	matGroup=enum:2
	color=color:43 41 35 255
	smoothAngle=float:60
	texture=string:OCODWATORRANDLOSHAUSKANTE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:ROPEWAY_MAT5
	matGroup=enum:3
	color=color:57 42 25 255
	smoothAngle=float:60
	texture=string:MOWOPLANKS05.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:ROPEWAY_MAT11
	matGroup=enum:3
	color=color:60 59 42 255
	smoothAngle=float:60
	texture=string:MOWOSHIP02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:ROPEWAY_MAT8
	matGroup=enum:3
	color=color:52 50 31 255
	smoothAngle=float:60
	texture=string:OCODWAWEHRGANGDA.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:OCODWABIGWOODLI
	matGroup=enum:3
	color=color:62 56 40 255
	smoothAngle=float:60
	texture=string:OCODWABIGWOODLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:OCODWARINGBRETTERLI
	matGroup=enum:3
	color=color:50 47 33 255
	smoothAngle=float:60
	texture=string:OCODWARINGBRETTERLI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:OCODWARINGBRETTERMI
	matGroup=enum:3
	color=color:51 48 33 255
	smoothAngle=float:60
	texture=string:OCODWARINGBRETTERMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:OCODWABRETTERWAND
	matGroup=enum:3
	color=color:50 46 33 255
	smoothAngle=float:60
	texture=string:OCODWABRETTERWAND.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:OCODWALIGHTWOODHALFMI
	matGroup=enum:3
	color=color:67 62 47 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODHALFMI.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:OCODWAOLDWOODSTONESLI
	matGroup=enum:3
	color=color:51 46 31 255
	smoothAngle=float:60
	texture=string:OCODWAOLDWOODSTONESLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 22]
	name=string:OCODWAOLDWOODSTONESDA
	matGroup=enum:3
	color=color:45 41 31 255
	smoothAngle=float:60
	texture=string:OCODWAOLDWOODSTONESDA.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 23]
	name=string:OCODWALIGHTWOODHALFLI
	matGroup=enum:3
	color=color:67 61 44 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODHALFLI.TGA
	texScale=string:64 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 24]
	name=string:OCODWALIGHTWOODAI
	matGroup=enum:3
	color=color:66 60 43 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODAI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 25]
	name=string:OCODWALIGHTWOODLI
	matGroup=enum:3
	color=color:64 59 44 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 26]
	name=string:OCODWALIGHTWOODBI
	matGroup=enum:3
	color=color:61 56 40 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODBI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 27]
	name=string:OCODWALIGHTWOODHALFBI
	matGroup=enum:3
	color=color:64 58 42 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODHALFBI.TGA
	texScale=string:64 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 28]
	name=string:OCODWALIGHTWOODHALFDA
	matGroup=enum:3
	color=color:61 56 41 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODHALFDA.TGA
	texScale=string:64 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 29]
	name=string:OCODWADARKTILE
	matGroup=enum:2
	color=color:15 9 5 255
	smoothAngle=float:60
	texture=string:OCODWADARKTILE.TGA
	texScale=string:32 32
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 30]
	name=string:OCODWALIGHTWOODMI.
	matGroup=enum:3
	color=color:60 55 40 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 31]
	name=string:OCODWADARKWOODMI
	matGroup=enum:3
	color=color:51 48 35 255
	smoothAngle=float:60
	texture=string:OCODWADARKWOODMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 32]
	name=string:OCODWADARKWOODHALFMI
	matGroup=enum:3
	color=color:53 49 36 255
	smoothAngle=float:60
	texture=string:OCODWADARKWOODHALFMI.TGA
	texScale=string:64 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 33]
	name=string:OCODWADARKWOODHALFLI
	matGroup=enum:3
	color=color:58 54 41 255
	smoothAngle=float:60
	texture=string:OCODWADARKWOODHALFLI.TGA
	texScale=string:64 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 34]
	name=string:OCODWADARKWOODLI
	matGroup=enum:3
	color=color:52 50 36 255
	smoothAngle=float:60
	texture=string:OCODWADARKWOODLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 35]
	name=string:OCODWALIGHTWOODHALFAI
	matGroup=enum:3
	color=color:65 60 43 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODHALFAI.TGA
	texScale=string:64 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 36]
	name=string:OCODWABIGWOODMI
	matGroup=enum:3
	color=color:54 48 38 255
	smoothAngle=float:60
	texture=string:OCODWABIGWOODMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 37]
	name=string:OCODWABIGWOODMILOD
	matGroup=enum:3
	color=color:54 48 38 255
	smoothAngle=float:60
	texture=string:OCODWABIGWOODMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:1
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 38]
	name=string:OC_OLDSAWHOUSE_V1_3
	matGroup=enum:3
	color=color:63 61 40 255
	smoothAngle=float:60
	texture=string:OCODWAWOODMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 39]
	name=string:OC_OLDSAWHOUSE_V1_5
	matGroup=enum:3
	color=color:54 48 38 255
	smoothAngle=float:60
	texture=string:OCODWABIGWOODMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 40]
	name=string:OLD_PSI_RICEHUT_02
	matGroup=enum:3
	color=color:52 50 36 255
	smoothAngle=float:60
	texture=string:OCODWADARKWOODLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 41]
	name=string:OCODWABRETTER1
	matGroup=enum:3
	color=color:50 46 33 255
	smoothAngle=float:60
	texture=string:OCODWABRETTERWAND.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 42]
	name=string:OWODWAOLDWOOD1
	matGroup=enum:3
	color=color:43 36 23 255
	smoothAngle=float:60
	texture=string:OWODWAOLDWOOD01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 43]
	name=string:OWODWAOLDWOOD2
	matGroup=enum:3
	color=color:43 36 23 255
	smoothAngle=float:60
	texture=string:OWODWAOLDWOOD01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 44]
	name=string:OCODWABIGWOOD1
	matGroup=enum:3
	color=color:54 48 38 255
	smoothAngle=float:60
	texture=string:OCODWABIGWOODMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 45]
	name=string:OCODWAWEHRGANGDA
	matGroup=enum:3
	color=color:52 50 31 255
	smoothAngle=float:60
	texture=string:OCODWAWEHRGANGDA.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 46]
	name=string:OCODWAWOODMI
	matGroup=enum:3
	color=color:63 61 40 255
	smoothAngle=float:60
	texture=string:OCODWAWOODMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 47]
	name=string:OCODWAWOODLI
	matGroup=enum:3
	color=color:74 67 45 255
	smoothAngle=float:60
	texture=string:OCODWAWOODLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 48]
	name=string:OCODWALATTEN
	matGroup=enum:3
	color=color:47 44 31 255
	smoothAngle=float:60
	texture=string:OCODWALATTEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 49]
	name=string:OCIDWAHUTWALLLI
	matGroup=enum:3
	color=color:56 49 34 255
	smoothAngle=float:60
	texture=string:OCIDWAHUTWALLLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 50]
	name=string:DTODWALATTEN
	matGroup=enum:3
	color=color:47 44 31 255
	smoothAngle=float:60
	texture=string:OCODWALATTEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 51]
	name=string:OCIDWAHUTWALLMI
	matGroup=enum:3
	color=color:42 39 28 255
	smoothAngle=float:60
	texture=string:OCIDWAHUTWALLMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 52]
	name=string:HOLTZ2
	matGroup=enum:3
	color=color:72 56 51 255
	smoothAngle=float:60
	texture=string:HOLTZ2.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 53]
	name=string:HOLZWALL
	matGroup=enum:3
	color=color:67 55 51 255
	smoothAngle=float:60
	texture=string:HOLZWALL.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 54]
	name=string:AL_W_DEF_IN_UP2
	matGroup=enum:3
	color=color:69 59 47 255
	smoothAngle=float:60
	texture=string:AL_W_DEF_IN_UP2.TGA
	texScale=string:256 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 55]
	name=string:MOWOBOWMARK01
	matGroup=enum:0
	color=color:69 41 31 255
	smoothAngle=float:60
	texture=string:MOWOBOWMARK01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 56]
	name=string:MOWODOOR01
	matGroup=enum:0
	color=color:39 29 26 255
	smoothAngle=float:60
	texture=string:MOWODOOR01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 57]
	name=string:MOWOLEVER01
	matGroup=enum:0
	color=color:57 44 37 255
	smoothAngle=float:60
	texture=string:MOWOLEVER01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 58]
	name=string:MOWOPLANKS02
	matGroup=enum:0
	color=color:70 62 49 255
	smoothAngle=float:60
	texture=string:MOWOPLANKS02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 59]
	name=string:MOWOPLANKS04
	matGroup=enum:0
	color=color:26 25 17 255
	smoothAngle=float:60
	texture=string:MOWOPLANKS04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 60]
	name=string:MOWOPLANKS09
	matGroup=enum:0
	color=color:49 47 32 255
	smoothAngle=float:60
	texture=string:MOWOPLANKS09.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 61]
	name=string:MOWOSTEPS01
	matGroup=enum:0
	color=color:56 51 36 255
	smoothAngle=float:60
	texture=string:MOWOSTEPS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 62]
	name=string:OCODWALIGHTWOODDA
	matGroup=enum:0
	color=color:64 58 41 255
	smoothAngle=float:60
	texture=string:OCODWALIGHTWOODDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 63]
	name=string:ORKODFLFLOORWOOD
	matGroup=enum:0
	color=color:57 53 31 255
	smoothAngle=float:60
	texture=string:ORKODFLFLOORWOOD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 64]
	name=string:ORKODWATRWALL05
	matGroup=enum:0
	color=color:69 55 40 255
	smoothAngle=float:60
	texture=string:ORKODWATRWALL05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 65]
	name=string:ORKODWATRWALL06
	matGroup=enum:0
	color=color:71 55 39 255
	smoothAngle=float:60
	texture=string:ORKODWATRWALL06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
