ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:57
user HornOx
END
objects 51       
END

[% zCMaterial 17408 0]
	name=string:IT_POTIONS
	matGroup=enum:0
	color=color:88 77 66 255
	smoothAngle=float:60
	texture=string:IT_POTIONS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:ITAMMUNITION
	matGroup=enum:0
	color=color:113 100 92 255
	smoothAngle=float:60
	texture=string:ITAMMUNITION.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:ITAR_SCROLLS
	matGroup=enum:0
	color=color:103 80 35 255
	smoothAngle=float:60
	texture=string:ITAR_SCROLLS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:ITARRUNES
	matGroup=enum:0
	color=color:49 51 43 255
	smoothAngle=float:60
	texture=string:ITARRUNES.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:ITFLAMEDBLADE
	matGroup=enum:0
	color=color:110 110 114 255
	smoothAngle=float:60
	texture=string:ITFLAMEDBLADE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:ITKEYS
	matGroup=enum:0
	color=color:41 31 18 255
	smoothAngle=float:60
	texture=string:ITKEYS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:ITMELEEBLADES
	matGroup=enum:0
	color=color:109 111 110 255
	smoothAngle=float:60
	texture=string:ITMELEEBLADES.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:ITMELEEORCWEAPONS
	matGroup=enum:0
	color=color:43 36 33 255
	smoothAngle=float:60
	texture=string:ITMELEEORCWEAPONS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:ITMELEEREST
	matGroup=enum:0
	color=color:66 56 49 255
	smoothAngle=float:60
	texture=string:ITMELEEREST.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:ITMICRAWLEREGG
	matGroup=enum:0
	color=color:146 136 122 255
	smoothAngle=float:60
	texture=string:ITMICRAWLEREGG.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:ITMIDRUM
	matGroup=enum:0
	color=color:163 143 130 255
	smoothAngle=float:60
	texture=string:ITMIDRUM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:ITMIDRUMSCHEIT
	matGroup=enum:0
	color=color:90 60 25 255
	smoothAngle=float:60
	texture=string:ITMIDRUMSCHEIT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:ITMIDUDELBLAU
	matGroup=enum:0
	color=color:98 102 111 255
	smoothAngle=float:60
	texture=string:ITMIDUDELBLAU.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:ITMIDUDELGELB
	matGroup=enum:0
	color=color:122 115 87 255
	smoothAngle=float:60
	texture=string:ITMIDUDELGELB.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:ITMIGONG
	matGroup=enum:0
	color=color:75 70 60 255
	smoothAngle=float:60
	texture=string:ITMIGONG.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:ITMIHARFE
	matGroup=enum:0
	color=color:125 95 48 255
	smoothAngle=float:60
	texture=string:ITMIHARFE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:ITMIHARFESAITE
	matGroup=enum:0
	color=color:190 190 190 255
	smoothAngle=float:60
	texture=string:ITMIHARFESAITE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:ITMILAUTE
	matGroup=enum:0
	color=color:77 68 61 255
	smoothAngle=float:60
	texture=string:ITMILAUTE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:ITMISAITE
	matGroup=enum:0
	color=color:223 223 223 255
	smoothAngle=float:60
	texture=string:ITMISAITE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:ITMISC
	matGroup=enum:0
	color=color:89 77 66 255
	smoothAngle=float:60
	texture=string:ITMISC.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:ITRANGEDWEAPONS
	matGroup=enum:0
	color=color:67 56 47 255
	smoothAngle=float:60
	texture=string:ITRANGEDWEAPONS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:ITRWORCSTAFF
	matGroup=enum:0
	color=color:84 64 58 255
	smoothAngle=float:60
	texture=string:ITRWORCSTAFF.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 22]
	name=string:ITWRITTEN
	matGroup=enum:0
	color=color:72 51 32 255
	smoothAngle=float:60
	texture=string:ITWRITTEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 23]
	name=string:MODIBACKPACK01
	matGroup=enum:0
	color=color:77 60 29 255
	smoothAngle=float:60
	texture=string:MODIBACKPACK01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 24]
	name=string:MODIBELLOW01
	matGroup=enum:0
	color=color:33 21 14 255
	smoothAngle=float:60
	texture=string:MODIBELLOW01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 25]
	name=string:MODIBOOKLET01
	matGroup=enum:0
	color=color:182 193 189 255
	smoothAngle=float:60
	texture=string:MODIBOOKLET01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 26]
	name=string:MODIBOOKS01
	matGroup=enum:0
	color=color:42 35 25 255
	smoothAngle=float:60
	texture=string:MODIBOOKS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 27]
	name=string:MODICARPET01
	matGroup=enum:0
	color=color:152 139 122 255
	smoothAngle=float:60
	texture=string:MODICARPET01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 28]
	name=string:MODIFLAG01
	matGroup=enum:0
	color=color:97 25 13 255
	smoothAngle=float:60
	texture=string:MODIFLAG01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 29]
	name=string:MODIHOLDER01
	matGroup=enum:0
	color=color:64 49 56 255
	smoothAngle=float:60
	texture=string:MODIHOLDER01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 30]
	name=string:MODIMAGICSTAFF01
	matGroup=enum:0
	color=color:78 67 57 255
	smoothAngle=float:60
	texture=string:MODIMAGICSTAFF01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 31]
	name=string:MODIPIPE01
	matGroup=enum:0
	color=color:116 88 37 255
	smoothAngle=float:60
	texture=string:MODIPIPE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 32]
	name=string:MODISKULL01
	matGroup=enum:0
	color=color:28 28 26 255
	smoothAngle=float:60
	texture=string:MODISKULL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 33]
	name=string:MODIVORHANG01
	matGroup=enum:0
	color=color:89 81 58 255
	smoothAngle=float:60
	texture=string:MODIVORHANG01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 34]
	name=string:MOMEBRAZIER
	matGroup=enum:0
	color=color:52 43 36 255
	smoothAngle=float:60
	texture=string:MOMEBRAZIER.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 35]
	name=string:MOMECHAIN02
	matGroup=enum:0
	color=color:14 13 13 255
	smoothAngle=float:60
	texture=string:MOMECHAIN02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 36]
	name=string:MOMEKETTLE01
	matGroup=enum:0
	color=color:55 43 33 255
	smoothAngle=float:60
	texture=string:MOMEKETTLE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 37]
	name=string:MOMELOCK01
	matGroup=enum:0
	color=color:40 38 37 255
	smoothAngle=float:60
	texture=string:MOMELOCK01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 38]
	name=string:MOMEMETALS01
	matGroup=enum:0
	color=color:87 91 88 255
	smoothAngle=float:60
	texture=string:MOMEMETALS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 39]
	name=string:MOMEMETALS02
	matGroup=enum:0
	color=color:41 40 40 255
	smoothAngle=float:60
	texture=string:MOMEMETALS02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 40]
	name=string:MOMEMETALS03
	matGroup=enum:0
	color=color:46 51 54 255
	smoothAngle=float:60
	texture=string:MOMEMETALS03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 41]
	name=string:MOMEORCSTAFF
	matGroup=enum:0
	color=color:95 89 62 255
	smoothAngle=float:60
	texture=string:MOMEORCSTAFF.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 42]
	name=string:MOSTFIREPLACE02
	matGroup=enum:0
	color=color:50 43 39 255
	smoothAngle=float:60
	texture=string:MOSTFIREPLACE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 43]
	name=string:MOSTSTONES02
	matGroup=enum:0
	color=color:66 58 46 255
	smoothAngle=float:60
	texture=string:MOSTSTONES02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 44]
	name=string:MOWOBEDS01
	matGroup=enum:0
	color=color:45 37 27 255
	smoothAngle=float:60
	texture=string:MOWOBEDS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 45]
	name=string:MOWODRUM01
	matGroup=enum:0
	color=color:163 143 130 255
	smoothAngle=float:60
	texture=string:MOWODRUM01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 46]
	name=string:MOWOFIREPLACE01
	matGroup=enum:0
	color=color:31 24 17 255
	smoothAngle=float:60
	texture=string:MOWOFIREPLACE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 47]
	name=string:MOWOMUSHROOM_01
	matGroup=enum:0
	color=color:122 106 100 255
	smoothAngle=float:60
	texture=string:MOWOMUSHROOM_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 48]
	name=string:MOWOTRON
	matGroup=enum:0
	color=color:66 52 42 255
	smoothAngle=float:60
	texture=string:MOWOTRON.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 49]
	name=string:ROPE
	matGroup=enum:0
	color=color:50 45 30 255
	smoothAngle=float:60
	texture=string:ROPE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 50]
	name=string:SKE_STOFFETZEN
	matGroup=enum:0
	color=color:22 26 25 255
	smoothAngle=float:60
	texture=string:SKE_STOFFETZEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
