ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:57
user HornOx
END
objects 31       
END

[% zCMaterial 17408 0]
	name=string:ABODEN
	matGroup=enum:0
	color=color:108 111 77 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:DEFAULT
	matGroup=enum:0
	color=color:0 0 0 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:PI:
	matGroup=enum:0
	color=color:0 0 0 0
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:KEINE
	matGroup=enum:0
	color=color:88 93 99 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:MODIALPHA01
	matGroup=enum:0
	color=color:249 250 250 255
	smoothAngle=float:60
	texture=string:MODIALPHA01.TGA
	texScale=string:4 4
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:GHOSTOCCLUDER
	matGroup=enum:0
	color=color:0 0 255 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:SUMPFWAASER
	matGroup=enum:0
	color=color:0 0 0 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:BLINDALPHA
	matGroup=enum:0
	color=color:249 250 250 255
	smoothAngle=float:60
	texture=string:MODIALPHA01.TGA
	texScale=string:4 4
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:BRETT2
	matGroup=enum:0
	color=color:55 37 26 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:BRETT1
	matGroup=enum:0
	color=color:132 88 62 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:KEINETEXTUREN
	matGroup=enum:0
	color=color:136 136 136 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:PI:ORCTEMPLE
	matGroup=enum:0
	color=color:0 0 0 0
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:STEIN4
	matGroup=enum:0
	color=color:57 56 51 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:STEIN24
	matGroup=enum:0
	color=color:117 114 79 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:BODEN2
	matGroup=enum:0
	color=color:106 88 77 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:STEIN3
	matGroup=enum:0
	color=color:56 56 56 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:FELS 1
	matGroup=enum:0
	color=color:96 96 96 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:STEIN21
	matGroup=enum:0
	color=color:117 114 79 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:SPACER_CHECK_CHANGE_LEVEL
	matGroup=enum:0
	color=color:27 19 5 255
	smoothAngle=float:60
	texture=string:SPACER_CHECK_CHANGE_LEVEL.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:SPACER_CHECK_TRIGGER_MOVER
	matGroup=enum:0
	color=color:27 21 6 255
	smoothAngle=float:60
	texture=string:SPACER_CHECK_TRIGGER_MOVER.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:SPACER_CHECK_MOB_INTERACT
	matGroup=enum:0
	color=color:27 19 5 255
	smoothAngle=float:60
	texture=string:SPACER_CHECK_MOB_INTERACT.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:SPACER_CHECK_LICHT_STATIC
	matGroup=enum:0
	color=color:27 17 5 255
	smoothAngle=float:60
	texture=string:SPACER_CHECK_LICHT_STATIC.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 22]
	name=string:SPACER_CHECK_LICHT_DYNAMIC
	matGroup=enum:0
	color=color:27 20 6 255
	smoothAngle=float:60
	texture=string:SPACER_CHECK_LICHT_DYNAMIC.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 23]
	name=string:FELSENHöHLE
	matGroup=enum:0
	color=color:97 97 97 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 24]
	name=string:NOPIDOPIE
	matGroup=enum:0
	color=color:82 82 82 255
	smoothAngle=float:60
	texture=string:
	texScale=string:1 1
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 25]
	name=string:RASTER5_BLAU
	matGroup=enum:0
	color=color:31 20 255 255
	smoothAngle=float:60
	texture=string:RASTER5_BLAU.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 26]
	name=string:RASTER5_GELB
	matGroup=enum:0
	color=color:255 241 20 255
	smoothAngle=float:60
	texture=string:RASTER5_GELB.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 27]
	name=string:SELECT
	matGroup=enum:0
	color=color:252 29 0 255
	smoothAngle=float:60
	texture=string:SELECT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 28]
	name=string:SPACER_CHECK_ITEM
	matGroup=enum:0
	color=color:26 9 4 255
	smoothAngle=float:60
	texture=string:SPACER_CHECK_ITEM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 29]
	name=string:SPACER_CHECK_KLETTERN
	matGroup=enum:0
	color=color:27 14 5 255
	smoothAngle=float:60
	texture=string:SPACER_CHECK_KLETTERN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 30]
	name=string:SPACER_CHECK_WASSER
	matGroup=enum:0
	color=color:27 13 5 255
	smoothAngle=float:60
	texture=string:SPACER_CHECK_WASSER.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
