ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:57
user HornOx
END
objects 22       
END

[% zCMaterial 17408 0]
	name=string:NCODWAPUTZ01
	matGroup=enum:0
	color=color:149 146 132 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:OCODWAHUTROOFMI
	matGroup=enum:3
	color=color:79 65 46 255
	smoothAngle=float:60
	texture=string:OCODWAHUTROOFMI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:NCODWAPUTZ07
	matGroup=enum:2
	color=color:135 132 112 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ07.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:OCODWAHUTROOFLI
	matGroup=enum:3
	color=color:88 76 56 255
	smoothAngle=float:60
	texture=string:OCODWAHUTROOFLI.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:NCODWAPUTZ10
	matGroup=enum:2
	color=color:125 121 101 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ10.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:NCODWAROOF03
	matGroup=enum:3
	color=color:124 113 91 255
	smoothAngle=float:60
	texture=string:NCODWAROOF03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:NCODWAPUTZ04
	matGroup=enum:2
	color=color:128 124 100 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ04.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:NCODWAPUTZ02
	matGroup=enum:2
	color=color:139 135 111 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ02.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:NCODWAPUTZ09
	matGroup=enum:2
	color=color:120 117 97 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ09.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:NCODWAPUTZ06
	matGroup=enum:2
	color=color:134 130 105 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ06.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:NCODWAPUTZ03
	matGroup=enum:2
	color=color:136 132 108 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ03.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:NCODWAPUTZ08
	matGroup=enum:2
	color=color:132 129 110 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ08.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:NCODWAPUTZ05
	matGroup=enum:2
	color=color:125 121 97 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ05.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:NCODWAPUTZ11
	matGroup=enum:2
	color=color:122 118 99 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ11.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:NCODWAPUTZ12
	matGroup=enum:2
	color=color:134 131 111 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZ12.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:NCODWAROOF02
	matGroup=enum:3
	color=color:107 100 83 255
	smoothAngle=float:60
	texture=string:NCODWAROOF02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:OCIDWAPUTZINSIDE
	matGroup=enum:2
	color=color:90 83 69 255
	smoothAngle=float:60
	texture=string:OCIDWAPUTZINSIDE.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:FMCODWAROOF
	matGroup=enum:3
	color=color:52 43 28 255
	smoothAngle=float:60
	texture=string:FMCODWAROOF.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:FMCODWADOOR
	matGroup=enum:2
	color=color:58 53 42 255
	smoothAngle=float:60
	texture=string:FMCODWADOOR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:FMCODWASIDE01
	matGroup=enum:2
	color=color:113 103 84 255
	smoothAngle=float:60
	texture=string:FMCODWASIDE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:FMCODWASIDE02
	matGroup=enum:2
	color=color:104 92 72 255
	smoothAngle=float:60
	texture=string:FMCODWASIDE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:NC_W_PORTAL_128
	matGroup=enum:0
	color=color:111 108 94 255
	smoothAngle=float:60
	texture=string:NC_W_PORTAL_128.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
