ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:57
user HornOx
END
objects 178      
END

[% zCMaterial 17408 0]
	name=string:AURA
	matGroup=enum:0
	color=color:43 33 20 255
	smoothAngle=float:60
	texture=string:AURA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:BLUEGLOW
	matGroup=enum:0
	color=color:18 24 27 255
	smoothAngle=float:60
	texture=string:BLUEGLOW.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:BLUESPARKLE0000
	matGroup=enum:0
	color=color:18 21 28 255
	smoothAngle=float:60
	texture=string:BLUESPARKLE0000.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:CFLAREBLUE
	matGroup=enum:0
	color=color:4 18 65 255
	smoothAngle=float:60
	texture=string:CFLAREBLUE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:CFLARERED1
	matGroup=enum:0
	color=color:67 54 66 255
	smoothAngle=float:60
	texture=string:CFLARERED1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:CFLARERED3
	matGroup=enum:0
	color=color:15 10 10 255
	smoothAngle=float:60
	texture=string:CFLARERED3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:CFLARERED
	matGroup=enum:0
	color=color:32 13 13 255
	smoothAngle=float:60
	texture=string:CFLARERED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:CFLARESTAR
	matGroup=enum:0
	color=color:15 15 15 255
	smoothAngle=float:60
	texture=string:CFLARESTAR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:COALGLOW
	matGroup=enum:0
	color=color:13 5 4 255
	smoothAngle=float:60
	texture=string:COALGLOW.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:CPFX_STONE
	matGroup=enum:0
	color=color:19 19 19 255
	smoothAngle=float:60
	texture=string:CPFX_STONE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:CPFX_WOOD
	matGroup=enum:0
	color=color:7 5 1 255
	smoothAngle=float:60
	texture=string:CPFX_WOOD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:DECAL_DEAMON_DISABLED
	matGroup=enum:0
	color=color:11 28 39 255
	smoothAngle=float:60
	texture=string:DECAL_DEAMON_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:DECAL_DEAMON
	matGroup=enum:0
	color=color:11 28 39 255
	smoothAngle=float:60
	texture=string:DECAL_DEAMON.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:DECAL_EARTHQUAKE_DISABLED
	matGroup=enum:0
	color=color:36 35 40 255
	smoothAngle=float:60
	texture=string:DECAL_EARTHQUAKE_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:DECAL_EARTHQUAKE
	matGroup=enum:0
	color=color:36 35 40 255
	smoothAngle=float:60
	texture=string:DECAL_EARTHQUAKE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:DECAL_FIREBALL_DISABLED
	matGroup=enum:0
	color=color:113 99 55 255
	smoothAngle=float:60
	texture=string:DECAL_FIREBALL_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:DECAL_FIREBALL
	matGroup=enum:0
	color=color:113 99 55 255
	smoothAngle=float:60
	texture=string:DECAL_FIREBALL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:DECAL_FORGET_DISABLED
	matGroup=enum:0
	color=color:44 63 37 255
	smoothAngle=float:60
	texture=string:DECAL_FORGET_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:DECAL_FORGET
	matGroup=enum:0
	color=color:44 63 37 255
	smoothAngle=float:60
	texture=string:DECAL_FORGET.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:DECAL_HEAL_DISABLED
	matGroup=enum:0
	color=color:61 50 65 255
	smoothAngle=float:60
	texture=string:DECAL_HEAL_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:DECAL_HEAL
	matGroup=enum:0
	color=color:61 50 65 255
	smoothAngle=float:60
	texture=string:DECAL_HEAL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:DECAL_HUMANCONTROL_DISABLED
	matGroup=enum:0
	color=color:25 17 63 255
	smoothAngle=float:60
	texture=string:DECAL_HUMANCONTROL_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 22]
	name=string:DECAL_HUMANCONTROL
	matGroup=enum:0
	color=color:25 17 63 255
	smoothAngle=float:60
	texture=string:DECAL_HUMANCONTROL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 23]
	name=string:DECAL_INSANE_DISABLED
	matGroup=enum:0
	color=color:29 5 20 255
	smoothAngle=float:60
	texture=string:DECAL_INSANE_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 24]
	name=string:DECAL_INSANE
	matGroup=enum:0
	color=color:29 5 20 255
	smoothAngle=float:60
	texture=string:DECAL_INSANE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 25]
	name=string:DECAL_INVISIBLE_DISABLED
	matGroup=enum:0
	color=color:11 12 30 255
	smoothAngle=float:60
	texture=string:DECAL_INVISIBLE_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 26]
	name=string:DECAL_INVISIBLE
	matGroup=enum:0
	color=color:11 12 30 255
	smoothAngle=float:60
	texture=string:DECAL_INVISIBLE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 27]
	name=string:DECAL_LIGHT_DISABLED
	matGroup=enum:0
	color=color:31 32 36 255
	smoothAngle=float:60
	texture=string:DECAL_LIGHT_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 28]
	name=string:DECAL_LIGHT
	matGroup=enum:0
	color=color:31 32 36 255
	smoothAngle=float:60
	texture=string:DECAL_LIGHT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 29]
	name=string:DECAL_LIGHTNING_DISABLED
	matGroup=enum:0
	color=color:5 5 5 255
	smoothAngle=float:60
	texture=string:DECAL_LIGHTNING_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 30]
	name=string:DECAL_LIGHTNING
	matGroup=enum:0
	color=color:5 5 5 255
	smoothAngle=float:60
	texture=string:DECAL_LIGHTNING.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 31]
	name=string:DECAL_STOPTIME_DISABLED
	matGroup=enum:0
	color=color:24 38 21 255
	smoothAngle=float:60
	texture=string:DECAL_STOPTIME_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 32]
	name=string:DECAL_STOPTIME
	matGroup=enum:0
	color=color:24 38 21 255
	smoothAngle=float:60
	texture=string:DECAL_STOPTIME.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 33]
	name=string:DECAL_TELEKINESIS_DISABLED
	matGroup=enum:0
	color=color:10 26 37 255
	smoothAngle=float:60
	texture=string:DECAL_TELEKINESIS_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 34]
	name=string:DECAL_TELEKINESIS
	matGroup=enum:0
	color=color:10 26 37 255
	smoothAngle=float:60
	texture=string:DECAL_TELEKINESIS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 35]
	name=string:DECAL_TELEPORTATION_DISABLED
	matGroup=enum:0
	color=color:57 68 68 255
	smoothAngle=float:60
	texture=string:DECAL_TELEPORTATION_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 36]
	name=string:DECAL_TELEPORTATION
	matGroup=enum:0
	color=color:57 68 68 255
	smoothAngle=float:60
	texture=string:DECAL_TELEPORTATION.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 37]
	name=string:DECAL_TELESTORM_DISABLED
	matGroup=enum:0
	color=color:44 63 37 255
	smoothAngle=float:60
	texture=string:DECAL_TELESTORM_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 38]
	name=string:DECAL_TELESTORM
	matGroup=enum:0
	color=color:44 63 37 255
	smoothAngle=float:60
	texture=string:DECAL_TELESTORM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 39]
	name=string:DECAL_TRANSFORM_DISABLED
	matGroup=enum:0
	color=color:44 11 34 255
	smoothAngle=float:60
	texture=string:DECAL_TRANSFORM_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 40]
	name=string:DECAL_TRANSFORM
	matGroup=enum:0
	color=color:44 11 34 255
	smoothAngle=float:60
	texture=string:DECAL_TRANSFORM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 41]
	name=string:DECAL_WINDFIST_DISABLED
	matGroup=enum:0
	color=color:62 18 19 255
	smoothAngle=float:60
	texture=string:DECAL_WINDFIST_DISABLED.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 42]
	name=string:DECAL_WINDFIST
	matGroup=enum:0
	color=color:62 18 19 255
	smoothAngle=float:60
	texture=string:DECAL_WINDFIST.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 43]
	name=string:DEMON_DIE
	matGroup=enum:0
	color=color:94 86 40 255
	smoothAngle=float:60
	texture=string:DEMON_DIE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 44]
	name=string:DEMONSIGN
	matGroup=enum:0
	color=color:55 4 35 255
	smoothAngle=float:60
	texture=string:DEMONSIGN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 45]
	name=string:DESTROYUNDEAD1
	matGroup=enum:0
	color=color:76 76 76 255
	smoothAngle=float:60
	texture=string:DESTROYUNDEAD1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 46]
	name=string:DESTROYUNDEAD2
	matGroup=enum:0
	color=color:49 49 49 255
	smoothAngle=float:60
	texture=string:DESTROYUNDEAD2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 47]
	name=string:DESTROYUNDEAD3
	matGroup=enum:0
	color=color:30 30 30 255
	smoothAngle=float:60
	texture=string:DESTROYUNDEAD3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 48]
	name=string:DOTS
	matGroup=enum:0
	color=color:1 1 1 255
	smoothAngle=float:60
	texture=string:DOTS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 49]
	name=string:DRUGPARTICLE
	matGroup=enum:0
	color=color:1 3 2 255
	smoothAngle=float:60
	texture=string:DRUGPARTICLE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 50]
	name=string:ECHOBRIGHT0000
	matGroup=enum:0
	color=color:57 68 68 255
	smoothAngle=float:60
	texture=string:ECHOBRIGHT0000.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 51]
	name=string:ELECTRICBLUE0000
	matGroup=enum:0
	color=color:11 12 30 255
	smoothAngle=float:60
	texture=string:ELECTRICBLUE0000.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 52]
	name=string:FIREBALL_16BIT
	matGroup=enum:0
	color=color:113 99 55 255
	smoothAngle=float:60
	texture=string:FIREBALL_16BIT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 53]
	name=string:FIREBALLQUADMARK
	matGroup=enum:0
	color=color:218 218 218 255
	smoothAngle=float:60
	texture=string:FIREBALLQUADMARK.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 54]
	name=string:FIREFLARE
	matGroup=enum:0
	color=color:159 106 28 255
	smoothAngle=float:60
	texture=string:FIREFLARE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 55]
	name=string:FIRESMOKE
	matGroup=enum:0
	color=color:128 117 107 255
	smoothAngle=float:60
	texture=string:FIRESMOKE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 56]
	name=string:FIRETAIL
	matGroup=enum:0
	color=color:68 37 22 255
	smoothAngle=float:60
	texture=string:FIRETAIL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 57]
	name=string:FLAME
	matGroup=enum:0
	color=color:16 14 6 255
	smoothAngle=float:60
	texture=string:FLAME.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 58]
	name=string:FLAREGREEN0000
	matGroup=enum:0
	color=color:24 38 21 255
	smoothAngle=float:60
	texture=string:FLAREGREEN0000.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 59]
	name=string:FLARESTAR
	matGroup=enum:0
	color=color:2 2 2 255
	smoothAngle=float:60
	texture=string:FLARESTAR.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 60]
	name=string:GALAXYYELLOW0000
	matGroup=enum:0
	color=color:66 32 0 255
	smoothAngle=float:60
	texture=string:GALAXYYELLOW0000.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 61]
	name=string:GLOWWORM_AURA_2
	matGroup=enum:0
	color=color:4 19 11 255
	smoothAngle=float:60
	texture=string:GLOWWORM_AURA_2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 62]
	name=string:GLOWWORM_AURA_3
	matGroup=enum:0
	color=color:3 16 9 255
	smoothAngle=float:60
	texture=string:GLOWWORM_AURA_3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 63]
	name=string:GLOWWORM_AURA_4
	matGroup=enum:0
	color=color:1 7 3 255
	smoothAngle=float:60
	texture=string:GLOWWORM_AURA_4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 64]
	name=string:GLOWWORM_AURA
	matGroup=enum:0
	color=color:8 27 18 255
	smoothAngle=float:60
	texture=string:GLOWWORM_AURA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 65]
	name=string:GLOWWORM
	matGroup=enum:0
	color=color:13 17 16 255
	smoothAngle=float:60
	texture=string:GLOWWORM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 66]
	name=string:HUMANBURN
	matGroup=enum:0
	color=color:21 14 5 255
	smoothAngle=float:60
	texture=string:HUMANBURN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 67]
	name=string:HUMANCTRL16BIT
	matGroup=enum:0
	color=color:25 17 63 255
	smoothAngle=float:60
	texture=string:HUMANCTRL16BIT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 68]
	name=string:LABDROPS
	matGroup=enum:0
	color=color:10 15 7 255
	smoothAngle=float:60
	texture=string:LABDROPS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 69]
	name=string:LABGLOW
	matGroup=enum:0
	color=color:5 17 5 255
	smoothAngle=float:60
	texture=string:LABGLOW.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 70]
	name=string:LABSMOKE
	matGroup=enum:0
	color=color:6 7 6 255
	smoothAngle=float:60
	texture=string:LABSMOKE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 71]
	name=string:LASERBEAM
	matGroup=enum:0
	color=color:161 163 165 255
	smoothAngle=float:60
	texture=string:LASERBEAM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 72]
	name=string:LAVAOUTBURST
	matGroup=enum:0
	color=color:83 53 18 255
	smoothAngle=float:60
	texture=string:LAVAOUTBURST.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 73]
	name=string:LIGHTNING_A1
	matGroup=enum:0
	color=color:58 67 65 255
	smoothAngle=float:60
	texture=string:LIGHTNING_A1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 74]
	name=string:LIGHTNING_A2
	matGroup=enum:0
	color=color:53 62 61 255
	smoothAngle=float:60
	texture=string:LIGHTNING_A2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 75]
	name=string:LIGHTNING_SINGLE
	matGroup=enum:0
	color=color:36 55 79 255
	smoothAngle=float:60
	texture=string:LIGHTNING_SINGLE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 76]
	name=string:LIGHTSPELL_16BIT
	matGroup=enum:0
	color=color:31 32 36 255
	smoothAngle=float:60
	texture=string:LIGHTSPELL_16BIT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 77]
	name=string:MAGICCOULDRON
	matGroup=enum:0
	color=color:20 20 20 255
	smoothAngle=float:60
	texture=string:MAGICCOULDRON.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 78]
	name=string:MAGICDUMMY16BIT_1
	matGroup=enum:0
	color=color:44 11 34 255
	smoothAngle=float:60
	texture=string:MAGICDUMMY16BIT_1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 79]
	name=string:MAGICDUMMY16BIT_2
	matGroup=enum:0
	color=color:36 35 40 255
	smoothAngle=float:60
	texture=string:MAGICDUMMY16BIT_2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 80]
	name=string:MAGICDUMMY16BIT_3
	matGroup=enum:0
	color=color:69 16 34 255
	smoothAngle=float:60
	texture=string:MAGICDUMMY16BIT_3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 81]
	name=string:MAGICDUMMY16BIT_4
	matGroup=enum:0
	color=color:61 50 65 255
	smoothAngle=float:60
	texture=string:MAGICDUMMY16BIT_4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 82]
	name=string:MAGICDUMMY16BIT_5
	matGroup=enum:0
	color=color:55 4 35 255
	smoothAngle=float:60
	texture=string:MAGICDUMMY16BIT_5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 83]
	name=string:MAGICDUMMY_1
	matGroup=enum:0
	color=color:44 11 34 255
	smoothAngle=float:60
	texture=string:MAGICDUMMY_1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 84]
	name=string:MAGICDUMMY_2
	matGroup=enum:0
	color=color:36 35 40 255
	smoothAngle=float:60
	texture=string:MAGICDUMMY_2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 85]
	name=string:MAGICFLARE
	matGroup=enum:0
	color=color:4 6 10 255
	smoothAngle=float:60
	texture=string:MAGICFLARE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 86]
	name=string:MAGICFOG
	matGroup=enum:0
	color=color:6 12 15 255
	smoothAngle=float:60
	texture=string:MAGICFOG.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 87]
	name=string:MFX_FIRERAIN_RAIN_BIG
	matGroup=enum:0
	color=color:55 31 13 255
	smoothAngle=float:60
	texture=string:MFX_FIRERAIN_RAIN_BIG.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 88]
	name=string:MFX_FIRERAIN_RAIN
	matGroup=enum:0
	color=color:40 24 8 255
	smoothAngle=float:60
	texture=string:MFX_FIRERAIN_RAIN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 89]
	name=string:MFX_FIRERAIN_RAINMARK
	matGroup=enum:0
	color=color:0 0 0 255
	smoothAngle=float:60
	texture=string:MFX_FIRERAIN_RAINMARK.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 90]
	name=string:MFX_FIRERAIN_RAINTRAIL
	matGroup=enum:0
	color=color:58 21 3 255
	smoothAngle=float:60
	texture=string:MFX_FIRERAIN_RAINTRAIL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 91]
	name=string:MFX_PYROKINESIS_TARGETTRAIL
	matGroup=enum:0
	color=color:124 92 67 255
	smoothAngle=float:60
	texture=string:MFX_PYROKINESIS_TARGETTRAIL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 92]
	name=string:MFX_THUNDERSPELL_ELECTRO
	matGroup=enum:0
	color=color:28 28 48 255
	smoothAngle=float:60
	texture=string:MFX_THUNDERSPELL_ELECTRO.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 93]
	name=string:OREGLOW
	matGroup=enum:0
	color=color:5 5 5 255
	smoothAngle=float:60
	texture=string:OREGLOW.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 94]
	name=string:OREHIGHLIGHT
	matGroup=enum:0
	color=color:2 2 2 255
	smoothAngle=float:60
	texture=string:OREHIGHLIGHT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 95]
	name=string:OTDEBLOOD_512
	matGroup=enum:0
	color=color:3 0 0 255
	smoothAngle=float:60
	texture=string:OTDEBLOOD_512.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 96]
	name=string:OTDEBLOOD_ZU DUNKEL
	matGroup=enum:0
	color=color:3 0 0 255
	smoothAngle=float:60
	texture=string:OTDEBLOOD_ZU DUNKEL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 97]
	name=string:OTDEBLOOD_ZUHELL
	matGroup=enum:0
	color=color:37 7 2 255
	smoothAngle=float:60
	texture=string:OTDEBLOOD_ZUHELL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 98]
	name=string:OTDEBLOOD
	matGroup=enum:0
	color=color:12 0 0 255
	smoothAngle=float:60
	texture=string:OTDEBLOOD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 99]
	name=string:OWDISPIDERWEB
	matGroup=enum:0
	color=color:76 76 76 255
	smoothAngle=float:60
	texture=string:OWDISPIDERWEB.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 100]
	name=string:PFXANI15
	matGroup=enum:0
	color=color:13 14 76 255
	smoothAngle=float:60
	texture=string:PFXANI15.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 101]
	name=string:PFXANI22
	matGroup=enum:0
	color=color:5 12 17 255
	smoothAngle=float:60
	texture=string:PFXANI22.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 102]
	name=string:PFXFLARE1
	matGroup=enum:0
	color=color:25 17 7 255
	smoothAngle=float:60
	texture=string:PFXFLARE1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 103]
	name=string:PFXFLARE3
	matGroup=enum:0
	color=color:25 17 7 255
	smoothAngle=float:60
	texture=string:PFXFLARE3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 104]
	name=string:PLASMA01
	matGroup=enum:0
	color=color:52 62 60 255
	smoothAngle=float:60
	texture=string:PLASMA01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 105]
	name=string:PLASMA02
	matGroup=enum:0
	color=color:57 67 65 255
	smoothAngle=float:60
	texture=string:PLASMA02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 106]
	name=string:PLASMA03
	matGroup=enum:0
	color=color:56 66 64 255
	smoothAngle=float:60
	texture=string:PLASMA03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 107]
	name=string:PSIDUMMY16BIT_1
	matGroup=enum:0
	color=color:44 63 37 255
	smoothAngle=float:60
	texture=string:PSIDUMMY16BIT_1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 108]
	name=string:PSIDUMMY16BIT_2
	matGroup=enum:0
	color=color:62 18 19 255
	smoothAngle=float:60
	texture=string:PSIDUMMY16BIT_2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 109]
	name=string:PSIDUMMY16BIT_3
	matGroup=enum:0
	color=color:10 26 37 255
	smoothAngle=float:60
	texture=string:PSIDUMMY16BIT_3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 110]
	name=string:PSIDUMMY16BIT_4
	matGroup=enum:0
	color=color:54 10 5 255
	smoothAngle=float:60
	texture=string:PSIDUMMY16BIT_4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 111]
	name=string:PSIDUMMY16BIT_5
	matGroup=enum:0
	color=color:29 5 20 255
	smoothAngle=float:60
	texture=string:PSIDUMMY16BIT_5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 112]
	name=string:PSIDUMMY_1
	matGroup=enum:0
	color=color:44 63 37 255
	smoothAngle=float:60
	texture=string:PSIDUMMY_1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 113]
	name=string:PSIDUMMY_2
	matGroup=enum:0
	color=color:62 18 19 255
	smoothAngle=float:60
	texture=string:PSIDUMMY_2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 114]
	name=string:PSIDUMMY_3
	matGroup=enum:0
	color=color:10 26 37 255
	smoothAngle=float:60
	texture=string:PSIDUMMY_3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 115]
	name=string:PSIDUMMY_4
	matGroup=enum:0
	color=color:54 10 5 255
	smoothAngle=float:60
	texture=string:PSIDUMMY_4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 116]
	name=string:PSIDUMMY_5
	matGroup=enum:0
	color=color:29 5 20 255
	smoothAngle=float:60
	texture=string:PSIDUMMY_5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 117]
	name=string:PUFF5
	matGroup=enum:0
	color=color:45 45 45 255
	smoothAngle=float:60
	texture=string:PUFF5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 118]
	name=string:PUFF
	matGroup=enum:0
	color=color:45 45 45 255
	smoothAngle=float:60
	texture=string:PUFF.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 119]
	name=string:SHOCKLIGHT
	matGroup=enum:0
	color=color:11 28 39 255
	smoothAngle=float:60
	texture=string:SHOCKLIGHT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 120]
	name=string:SIMPLEGLOW
	matGroup=enum:0
	color=color:38 38 38 255
	smoothAngle=float:60
	texture=string:SIMPLEGLOW.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 121]
	name=string:SUN_00
	matGroup=enum:0
	color=color:15 10 10 255
	smoothAngle=float:60
	texture=string:SUN_00.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 122]
	name=string:SUN_01
	matGroup=enum:0
	color=color:32 32 14 255
	smoothAngle=float:60
	texture=string:SUN_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 123]
	name=string:SUN_02
	matGroup=enum:0
	color=color:7 7 39 255
	smoothAngle=float:60
	texture=string:SUN_02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 124]
	name=string:SUN_03
	matGroup=enum:0
	color=color:20 19 48 255
	smoothAngle=float:60
	texture=string:SUN_03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 125]
	name=string:SUN_04
	matGroup=enum:0
	color=color:14 13 9 255
	smoothAngle=float:60
	texture=string:SUN_04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 126]
	name=string:SUN_05
	matGroup=enum:0
	color=color:25 26 27 255
	smoothAngle=float:60
	texture=string:SUN_05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 127]
	name=string:TELSTURM
	matGroup=enum:0
	color=color:5 5 8 255
	smoothAngle=float:60
	texture=string:TELSTURM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 128]
	name=string:TORCHFLAME2
	matGroup=enum:0
	color=color:10 8 4 255
	smoothAngle=float:60
	texture=string:TORCHFLAME2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 129]
	name=string:TORCHFLAME
	matGroup=enum:0
	color=color:13 10 5 255
	smoothAngle=float:60
	texture=string:TORCHFLAME.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 130]
	name=string:UNSUN5
	matGroup=enum:0
	color=color:21 22 23 255
	smoothAngle=float:60
	texture=string:UNSUN5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 131]
	name=string:WATER_BOOM
	matGroup=enum:0
	color=color:62 63 64 255
	smoothAngle=float:60
	texture=string:WATER_BOOM.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 132]
	name=string:WATERRING
	matGroup=enum:0
	color=color:24 24 24 255
	smoothAngle=float:60
	texture=string:WATERRING.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 133]
	name=string:WATERSPLASH1
	matGroup=enum:0
	color=color:20 20 20 255
	smoothAngle=float:60
	texture=string:WATERSPLASH1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 134]
	name=string:WF_SINGLE1
	matGroup=enum:0
	color=color:12 13 13 255
	smoothAngle=float:60
	texture=string:WF_SINGLE1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 135]
	name=string:WF_SINGLE2
	matGroup=enum:0
	color=color:204 214 216 255
	smoothAngle=float:60
	texture=string:WF_SINGLE2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 136]
	name=string:WHITECLOUD
	matGroup=enum:0
	color=color:19 19 19 255
	smoothAngle=float:60
	texture=string:WHITECLOUD.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 137]
	name=string:XBEAM1
	matGroup=enum:0
	color=color:67 61 60 255
	smoothAngle=float:60
	texture=string:XBEAM1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 138]
	name=string:XBEAM2
	matGroup=enum:0
	color=color:87 0 0 255
	smoothAngle=float:60
	texture=string:XBEAM2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 139]
	name=string:XBEAM3
	matGroup=enum:0
	color=color:100 102 100 255
	smoothAngle=float:60
	texture=string:XBEAM3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 140]
	name=string:XBEAM4
	matGroup=enum:0
	color=color:16 16 16 255
	smoothAngle=float:60
	texture=string:XBEAM4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 141]
	name=string:XBEAM5
	matGroup=enum:0
	color=color:86 72 73 255
	smoothAngle=float:60
	texture=string:XBEAM5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 142]
	name=string:ZBEAM1
	matGroup=enum:0
	color=color:75 66 18 255
	smoothAngle=float:60
	texture=string:ZBEAM1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 143]
	name=string:ZBEAM2
	matGroup=enum:0
	color=color:63 64 63 255
	smoothAngle=float:60
	texture=string:ZBEAM2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 144]
	name=string:ZBEAM3
	matGroup=enum:0
	color=color:85 87 85 255
	smoothAngle=float:60
	texture=string:ZBEAM3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 145]
	name=string:ZBEAM4
	matGroup=enum:0
	color=color:145 147 145 255
	smoothAngle=float:60
	texture=string:ZBEAM4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 146]
	name=string:ZBEAM5
	matGroup=enum:0
	color=color:59 60 59 255
	smoothAngle=float:60
	texture=string:ZBEAM5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 147]
	name=string:ZBEAM6
	matGroup=enum:0
	color=color:74 77 74 255
	smoothAngle=float:60
	texture=string:ZBEAM6.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 148]
	name=string:ZBLOODPOOL
	matGroup=enum:0
	color=color:21 0 0 255
	smoothAngle=float:60
	texture=string:ZBLOODPOOL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 149]
	name=string:ZBLOODSPLAT0
	matGroup=enum:0
	color=color:42 3 2 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 150]
	name=string:ZBLOODSPLAT1
	matGroup=enum:0
	color=color:11 0 1 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 151]
	name=string:ZBLOODSPLAT2
	matGroup=enum:0
	color=color:15 0 0 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 152]
	name=string:ZBLOODSPLAT3
	matGroup=enum:0
	color=color:47 3 5 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 153]
	name=string:ZBLOODSPLAT4
	matGroup=enum:0
	color=color:4 0 0 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT4.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 154]
	name=string:ZBLOODSPLAT5
	matGroup=enum:0
	color=color:4 0 0 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 155]
	name=string:ZBLOODSPLAT6
	matGroup=enum:0
	color=color:13 0 0 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT6.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 156]
	name=string:ZBLOODSPLAT7
	matGroup=enum:0
	color=color:10 0 0 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT7.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 157]
	name=string:ZBLOODSPLAT8
	matGroup=enum:0
	color=color:4 0 0 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT8.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 158]
	name=string:ZBLOODSPLAT9
	matGroup=enum:0
	color=color:28 0 0 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT9.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 159]
	name=string:ZBLOODSPLAT10
	matGroup=enum:0
	color=color:38 2 2 255
	smoothAngle=float:60
	texture=string:ZBLOODSPLAT10.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 160]
	name=string:ZBLOODSPOT
	matGroup=enum:0
	color=color:28 0 0 255
	smoothAngle=float:60
	texture=string:ZBLOODSPOT.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 161]
	name=string:ZFLARE1
	matGroup=enum:0
	color=color:36 35 34 255
	smoothAngle=float:60
	texture=string:ZFLARE1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 162]
	name=string:ZFLARE2
	matGroup=enum:0
	color=color:25 26 27 255
	smoothAngle=float:60
	texture=string:ZFLARE2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 163]
	name=string:ZFLARE6
	matGroup=enum:0
	color=color:50 28 8 255
	smoothAngle=float:60
	texture=string:ZFLARE6.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 164]
	name=string:ZPLASMA0
	matGroup=enum:0
	color=color:107 107 107 255
	smoothAngle=float:60
	texture=string:ZPLASMA0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 165]
	name=string:ZPLASMA1
	matGroup=enum:0
	color=color:107 107 107 255
	smoothAngle=float:60
	texture=string:ZPLASMA1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 166]
	name=string:ZSPARK1
	matGroup=enum:0
	color=color:7 6 4 255
	smoothAngle=float:60
	texture=string:ZSPARK1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 167]
	name=string:ZWEAPONTRAIL
	matGroup=enum:0
	color=color:127 127 127 255
	smoothAngle=float:60
	texture=string:ZWEAPONTRAIL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 168]
	name=string:ALIEN0000
	matGroup=enum:0
	color=color:13 35 17 255
	smoothAngle=float:60
	texture=string:ALIEN0000.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 169]
	name=string:EXPLAERIAL_A0
	matGroup=enum:0
	color=color:76 70 62 255
	smoothAngle=float:60
	texture=string:EXPLAERIAL_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 170]
	name=string:FIRE2_A0
	matGroup=enum:0
	color=color:26 20 14 255
	smoothAngle=float:60
	texture=string:FIRE2_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 171]
	name=string:FIREBALL_A0
	matGroup=enum:0
	color=color:113 98 66 255
	smoothAngle=float:60
	texture=string:FIREBALL_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 172]
	name=string:FLAME_A0
	matGroup=enum:0
	color=color:42 39 28 255
	smoothAngle=float:60
	texture=string:FLAME_A0.TGA
	texScale=string:256 256
	texAniFPS=float:7
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 173]
	name=string:PFX4_A0
	matGroup=enum:0
	color=color:2 2 8 255
	smoothAngle=float:60
	texture=string:PFX4_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 174]
	name=string:PFX6_A0
	matGroup=enum:0
	color=color:7 8 2 255
	smoothAngle=float:60
	texture=string:PFX6_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 175]
	name=string:PFX13_A0
	matGroup=enum:0
	color=color:5 8 9 255
	smoothAngle=float:60
	texture=string:PFX13_A0.TGA
	texScale=string:256 256
	texAniFPS=float:6
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 176]
	name=string:PFXFEXP2_A0
	matGroup=enum:0
	color=color:19 14 1 255
	smoothAngle=float:60
	texture=string:PFXFEXP2_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 177]
	name=string:PFXFLARE2_A0
	matGroup=enum:0
	color=color:13 15 19 255
	smoothAngle=float:60
	texture=string:PFXFLARE2_A0.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
