ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:57
user HornOx
END
objects 8        
END

[% zCMaterial 17408 0]
	name=string:OTWABLACKMARBEL03
	matGroup=enum:2
	color=color:13 10 10 255
	smoothAngle=float:60
	texture=string:OTWABLACKMARBEL03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:OTWABLACKMARBEL01
	matGroup=enum:2
	color=color:6 8 8 255
	smoothAngle=float:60
	texture=string:OTWABLACKMARBEL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:OTWABLACKMARBEL04
	matGroup=enum:2
	color=color:16 11 11 255
	smoothAngle=float:60
	texture=string:OTWABLACKMARBEL04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:OTWABLACKMARBEL05
	matGroup=enum:2
	color=color:79 69 60 255
	smoothAngle=float:60
	texture=string:OTWABLACKMARBEL05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:OTWABLACKMARBEL06
	matGroup=enum:2
	color=color:11 13 13 255
	smoothAngle=float:60
	texture=string:OTWABLACKMARBEL06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:OTWABLACKMARBEL02
	matGroup=enum:2
	color=color:32 23 18 255
	smoothAngle=float:60
	texture=string:OTWABLACKMARBEL02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:OTWABLACKMARBEL02 
	matGroup=enum:0
	color=color:39 29 24 255
	smoothAngle=float:60
	texture=string:OTWABLACKMARBEL02 .TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:OTWASYMBOL
	matGroup=enum:0
	color=color:35 11 9 255
	smoothAngle=float:60
	texture=string:OTWASYMBOL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
