ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 27.6.2002 22:52:57
user HornOx
END
objects 116      
END

[% zCMaterial 17408 0]
	name=string:ORKODREFLOOR02
	matGroup=enum:2
	color=color:45 37 33 255
	smoothAngle=float:60
	texture=string:ORKODREFLOOR02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 1]
	name=string:ORKODREFLOOR05
	matGroup=enum:2
	color=color:50 41 32 255
	smoothAngle=float:60
	texture=string:ORKODREFLOOR05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 2]
	name=string:ORKODREFLOOR08
	matGroup=enum:0
	color=color:49 31 22 255
	smoothAngle=float:60
	texture=string:ORKODREFLOOR03.TGA
	texScale=string:256 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 3]
	name=string:ORKODREFLOOR04
	matGroup=enum:0
	color=color:50 41 32 255
	smoothAngle=float:60
	texture=string:ORKODREFLOOR05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 4]
	name=string:NCODFLKACHELN
	matGroup=enum:0
	color=color:72 59 51 255
	smoothAngle=float:60
	texture=string:NCODFLKACHELN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 5]
	name=string:ORNAFLOR
	matGroup=enum:0
	color=color:126 111 97 255
	smoothAngle=float:60
	texture=string:ORNAFLOR.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 6]
	name=string:OTRESTONE01
	matGroup=enum:0
	color=color:71 63 48 255
	smoothAngle=float:60
	texture=string:OTRESTONE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 7]
	name=string:RAHMEN
	matGroup=enum:0
	color=color:59 53 37 255
	smoothAngle=float:60
	texture=string:OTRESTONE03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 8]
	name=string:OTWABILDVIELE1
	matGroup=enum:0
	color=color:100 94 83 255
	smoothAngle=float:60
	texture=string:OTWABILDVIELE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 9]
	name=string:OTRESTONE02
	matGroup=enum:2
	color=color:60 54 42 255
	smoothAngle=float:60
	texture=string:OTRESTONE02.TGA
	texScale=string:256 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 10]
	name=string:PSI_ABHAENGE_SEIL
	matGroup=enum:0
	color=color:61 48 9 255
	smoothAngle=float:60
	texture=string:MODIRAIL01.TGA
	texScale=string:32 32
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 11]
	name=string:PSI_TEMPEL_ORNAMENTS
	matGroup=enum:0
	color=color:72 64 50 255
	smoothAngle=float:60
	texture=string:OTDOORNAMENT01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 12]
	name=string:OWODWASKULLTEETH
	matGroup=enum:2
	color=color:82 79 67 255
	smoothAngle=float:60
	texture=string:OWODWASKULLTEETH.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 13]
	name=string:OWODWASKULLEYE
	matGroup=enum:2
	color=color:111 107 90 255
	smoothAngle=float:60
	texture=string:OWODWASKULLEYE.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 14]
	name=string:OTRETILE01
	matGroup=enum:2
	color=color:112 98 77 255
	smoothAngle=float:60
	texture=string:OTRETILE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 15]
	name=string:OTWABILDVIELE
	matGroup=enum:2
	color=color:100 94 83 255
	smoothAngle=float:60
	texture=string:OTWABILDVIELE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 16]
	name=string:OTWASTONELI02
	matGroup=enum:2
	color=color:87 78 60 255
	smoothAngle=float:60
	texture=string:OTWASTONELI02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 17]
	name=string:OTRESTONE03
	matGroup=enum:0
	color=color:59 53 37 255
	smoothAngle=float:60
	texture=string:OTRESTONE03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 18]
	name=string:OTWARELIEFMI
	matGroup=enum:0
	color=color:64 60 50 255
	smoothAngle=float:60
	texture=string:OTWARELIEFMI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 19]
	name=string:ROPEWAY_MAT1
	matGroup=enum:0
	color=color:37 33 26 255
	smoothAngle=float:60
	texture=string:MOMECHAIN01.TGA
	texScale=string:64 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 20]
	name=string:ROPEWAY_MAT10
	matGroup=enum:0
	color=color:78 73 44 255
	smoothAngle=float:60
	texture=string:MOWOSHIP01.TGA
	texScale=string:64 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 21]
	name=string:NCODWATILE
	matGroup=enum:2
	color=color:76 77 66 255
	smoothAngle=float:60
	texture=string:NCODWATILE.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 22]
	name=string:NCODWAPUTZORNAMENTLI
	matGroup=enum:2
	color=color:78 81 64 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZORNAMENTLI.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 23]
	name=string:NCODWATILERUNE03
	matGroup=enum:2
	color=color:72 73 63 255
	smoothAngle=float:60
	texture=string:NCODWATILERUNE03.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 24]
	name=string:NCODWATILERUNE02
	matGroup=enum:2
	color=color:72 74 63 255
	smoothAngle=float:60
	texture=string:NCODWATILERUNE02.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 25]
	name=string:NCODWAPUTZORNAMENTDA
	matGroup=enum:2
	color=color:85 83 63 255
	smoothAngle=float:60
	texture=string:NCODWAPUTZORNAMENTDA.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 26]
	name=string:OCODFLSTONESTEPLI
	matGroup=enum:2
	color=color:72 66 54 255
	smoothAngle=float:60
	texture=string:OCODFLSTONESTEPLI.TGA
	texScale=string:256 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 27]
	name=string:OTRESTONE04A
	matGroup=enum:2
	color=color:100 87 64 255
	smoothAngle=float:60
	texture=string:OTRESTONE04A.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 28]
	name=string:OTRE4TILES
	matGroup=enum:2
	color=color:122 104 71 255
	smoothAngle=float:60
	texture=string:OTRE4TILES.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 29]
	name=string:OTREKRALLE01
	matGroup=enum:0
	color=color:48 40 29 255
	smoothAngle=float:60
	texture=string:OTREKRALLE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 30]
	name=string:OTWAWALLRELIEF01
	matGroup=enum:2
	color=color:85 59 41 255
	smoothAngle=float:60
	texture=string:OTWAWALLRELIEF01.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 31]
	name=string:OTRE21
	matGroup=enum:0
	color=color:101 91 73 255
	smoothAngle=float:60
	texture=string:OTRE21.TGA
	texScale=string:256 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 32]
	name=string:OTRE20
	matGroup=enum:2
	color=color:108 95 67 255
	smoothAngle=float:60
	texture=string:OTRE20.TGA
	texScale=string:64 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 33]
	name=string:OTWASTONELI04
	matGroup=enum:2
	color=color:75 69 54 255
	smoothAngle=float:60
	texture=string:OTWASTONELI04.TGA
	texScale=string:256 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 34]
	name=string:OWODWASKULLTE1
	matGroup=enum:0
	color=color:82 79 67 255
	smoothAngle=float:60
	texture=string:OWODWASKULLTEETH.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 35]
	name=string:NCODWATILERUNE01
	matGroup=enum:2
	color=color:72 74 63 255
	smoothAngle=float:60
	texture=string:NCODWATILERUNE01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 36]
	name=string:OTWASTONELI022
	matGroup=enum:0
	color=color:87 78 60 255
	smoothAngle=float:60
	texture=string:OTWASTONELI02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 37]
	name=string:OTWAMARBEL01
	matGroup=enum:0
	color=color:100 97 86 255
	smoothAngle=float:60
	texture=string:OTWAMARBEL01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 38]
	name=string:OTDOMETALSTRIPES01
	matGroup=enum:0
	color=color:9 9 8 255
	smoothAngle=float:60
	texture=string:OTDOMETALSTRIPES01.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 39]
	name=string:OTWABLACKMARBEL07
	matGroup=enum:0
	color=color:30 27 27 255
	smoothAngle=float:60
	texture=string:OTWABLACKMARBEL07.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 40]
	name=string:OTWADECKENBALKEN
	matGroup=enum:0
	color=color:134 128 111 255
	smoothAngle=float:60
	texture=string:OTWADECKENBALKEN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 41]
	name=string:OTWASTONELI03
	matGroup=enum:0
	color=color:85 75 58 255
	smoothAngle=float:60
	texture=string:OTWASTONELI03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 42]
	name=string:OTWABILDDA08
	matGroup=enum:0
	color=color:92 82 63 255
	smoothAngle=float:60
	texture=string:OTWABILDDA08.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 43]
	name=string:OTWABILDDA10
	matGroup=enum:0
	color=color:96 86 67 255
	smoothAngle=float:60
	texture=string:OTWABILDDA10.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 44]
	name=string:OTWABILDDA07
	matGroup=enum:0
	color=color:67 64 51 255
	smoothAngle=float:60
	texture=string:OTWABILDDA07.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 45]
	name=string:OTWABILDDA09
	matGroup=enum:0
	color=color:89 81 63 255
	smoothAngle=float:60
	texture=string:OTWABILDDA09.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 46]
	name=string:OTWABILDDA06
	matGroup=enum:0
	color=color:67 63 47 255
	smoothAngle=float:60
	texture=string:OTWABILDDA06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 47]
	name=string:OTWABILDDA11
	matGroup=enum:0
	color=color:91 82 62 255
	smoothAngle=float:60
	texture=string:OTWABILDDA11.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 48]
	name=string:OTREKRALLE03
	matGroup=enum:0
	color=color:54 56 43 255
	smoothAngle=float:60
	texture=string:OTREKRALLE03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 49]
	name=string:OTREGITTER02
	matGroup=enum:0
	color=color:41 23 31 255
	smoothAngle=float:60
	texture=string:OTREGITTER02.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 50]
	name=string:OTDOORNAMENT02
	matGroup=enum:0
	color=color:83 75 58 255
	smoothAngle=float:60
	texture=string:OTDOORNAMENT02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 51]
	name=string:OTDOORNAMENT01
	matGroup=enum:0
	color=color:72 64 50 255
	smoothAngle=float:60
	texture=string:OTDOORNAMENT01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 52]
	name=string:OTRESTONE04
	matGroup=enum:0
	color=color:95 82 60 255
	smoothAngle=float:60
	texture=string:OTRESTONE04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 53]
	name=string:OTREGITTER01
	matGroup=enum:0
	color=color:51 49 38 255
	smoothAngle=float:60
	texture=string:OTREGITTER01.TGA
	texScale=string:64 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 54]
	name=string:OTWABILDLI02
	matGroup=enum:0
	color=color:82 84 70 255
	smoothAngle=float:60
	texture=string:OTWABILDLI02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 55]
	name=string:OTWABILDLI00
	matGroup=enum:0
	color=color:82 84 70 255
	smoothAngle=float:60
	texture=string:OTWABILDLI00.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 56]
	name=string:OTREBODENORANMENT02
	matGroup=enum:0
	color=color:71 68 57 255
	smoothAngle=float:60
	texture=string:OTREBODENORANMENT02.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 57]
	name=string:OTREBODENORANMENT01
	matGroup=enum:0
	color=color:125 72 61 255
	smoothAngle=float:60
	texture=string:OTREBODENORANMENT01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 58]
	name=string:OTDOSTONELI01
	matGroup=enum:0
	color=color:89 79 60 255
	smoothAngle=float:60
	texture=string:OTDOSTONELI01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 59]
	name=string:OTWABILDLI01
	matGroup=enum:0
	color=color:80 82 68 255
	smoothAngle=float:60
	texture=string:OTWABILDLI01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 60]
	name=string:OTTRSITAL
	matGroup=enum:0
	color=color:97 92 74 255
	smoothAngle=float:60
	texture=string:OTTRSITAL.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 61]
	name=string:OTWASITALABSCHLUS
	matGroup=enum:0
	color=color:105 96 70 255
	smoothAngle=float:60
	texture=string:OTWASITALABSCHLUS.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 62]
	name=string:OTWASITALDAPLAIN
	matGroup=enum:0
	color=color:32 31 30 255
	smoothAngle=float:60
	texture=string:OTWASITALDAPLAIN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 63]
	name=string:OTWASITALRE6
	matGroup=enum:0
	color=color:93 90 73 255
	smoothAngle=float:60
	texture=string:OTWASITALRE6.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 64]
	name=string:OTWASITALDARE1
	matGroup=enum:0
	color=color:37 36 36 255
	smoothAngle=float:60
	texture=string:OTWASITALDARE1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 65]
	name=string:OTWASITALRE3
	matGroup=enum:0
	color=color:99 91 66 255
	smoothAngle=float:60
	texture=string:OTWASITALRE3.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 66]
	name=string:OTWASTONELI01
	matGroup=enum:0
	color=color:111 97 74 255
	smoothAngle=float:60
	texture=string:OTWASTONELI01.TGA
	texScale=string:256 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 67]
	name=string:OTREFLOOR01
	matGroup=enum:0
	color=color:86 94 89 255
	smoothAngle=float:60
	texture=string:OTREFLOOR01.TGA
	texScale=string:128 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 68]
	name=string:OTWABILDDA05
	matGroup=enum:0
	color=color:59 58 44 255
	smoothAngle=float:60
	texture=string:OTWABILDDA04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 69]
	name=string:OTREMULTI01
	matGroup=enum:0
	color=color:87 79 60 255
	smoothAngle=float:60
	texture=string:OTREMULTI01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 70]
	name=string:OTWABILDDA02
	matGroup=enum:0
	color=color:95 91 67 255
	smoothAngle=float:60
	texture=string:OTWABILDDA02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 71]
	name=string:OTWASITALRE5
	matGroup=enum:0
	color=color:94 86 63 255
	smoothAngle=float:60
	texture=string:OTWASITALRE5.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 72]
	name=string:OTWAMARBEL02
	matGroup=enum:0
	color=color:97 94 84 255
	smoothAngle=float:60
	texture=string:OTWAMARBEL02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 73]
	name=string:OTWATARGETSTONESYMBOL_01
	matGroup=enum:0
	color=color:104 95 69 255
	smoothAngle=float:60
	texture=string:OTWATARGETSTONEFRESCO.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 74]
	name=string:OTWASITALRE4
	matGroup=enum:0
	color=color:106 97 67 255
	smoothAngle=float:60
	texture=string:OTWASITALRE4.TGA
	texScale=string:64 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 75]
	name=string:OTWAMARBEL06
	matGroup=enum:0
	color=color:24 21 15 255
	smoothAngle=float:60
	texture=string:OTWAMARBEL06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 76]
	name=string:OTWAMARBEL05
	matGroup=enum:0
	color=color:85 83 73 255
	smoothAngle=float:60
	texture=string:OTWAMARBEL05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 77]
	name=string:OTWABLOODLINE
	matGroup=enum:0
	color=color:70 63 54 255
	smoothAngle=float:60
	texture=string:OTWABLOODLINE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 78]
	name=string:TEMPLE_OTWASYMBOL_DIE
	matGroup=enum:0
	color=color:108 99 71 255
	smoothAngle=float:60
	texture=string:OTWASYMBOLDIE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 79]
	name=string:TEMPLE_OTWASYMBOL_LIFE
	matGroup=enum:0
	color=color:104 95 68 255
	smoothAngle=float:60
	texture=string:OTWASYMBOLLIVE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 80]
	name=string:TEMPLE_OTWAMASKFIRE
	matGroup=enum:0
	color=color:95 71 49 255
	smoothAngle=float:60
	texture=string:OTWAMASKFIRE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 81]
	name=string:TEMPLE_OTWAMASKMOON
	matGroup=enum:0
	color=color:73 58 58 255
	smoothAngle=float:60
	texture=string:OTWAMASKMOON.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 82]
	name=string:TEMPLE_OTWAMASKSUN
	matGroup=enum:0
	color=color:94 86 56 255
	smoothAngle=float:60
	texture=string:OTWAMASKSUN.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 83]
	name=string:OTWAMARBEL02A KOPIE
	matGroup=enum:0
	color=color:51 48 40 255
	smoothAngle=float:60
	texture=string:OTWAMARBEL02A KOPIE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 84]
	name=string:OTWASPIKESSYMBOLS_01
	matGroup=enum:0
	color=color:95 87 62 255
	smoothAngle=float:60
	texture=string:OTWASPIKESFRESCO.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 85]
	name=string:OTWASITALRE2
	matGroup=enum:0
	color=color:96 88 63 255
	smoothAngle=float:60
	texture=string:OTWASITALRE2.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 86]
	name=string:OTWAMARBEL04
	matGroup=enum:0
	color=color:95 93 83 255
	smoothAngle=float:60
	texture=string:OTWAMARBEL04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 87]
	name=string:OTWAMARBEL03
	matGroup=enum:0
	color=color:92 90 79 255
	smoothAngle=float:60
	texture=string:OTWAMARBEL03.TGA
	texScale=string:64 64
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 88]
	name=string:AL_W_CELLAR
	matGroup=enum:0
	color=color:96 94 84 255
	smoothAngle=float:60
	texture=string:AL_W_CELLAR.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:9.9999997e-005 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 89]
	name=string:MODERUNE01
	matGroup=enum:0
	color=color:105 105 105 255
	smoothAngle=float:60
	texture=string:MODERUNE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 90]
	name=string:MODERUNE02
	matGroup=enum:0
	color=color:105 105 105 255
	smoothAngle=float:60
	texture=string:MODERUNE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 91]
	name=string:MODERUNE03
	matGroup=enum:0
	color=color:101 100 100 255
	smoothAngle=float:60
	texture=string:MODERUNE03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 92]
	name=string:MODERUNE04
	matGroup=enum:0
	color=color:104 104 104 255
	smoothAngle=float:60
	texture=string:MODERUNE04.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 93]
	name=string:MODERUNE05
	matGroup=enum:0
	color=color:100 101 101 255
	smoothAngle=float:60
	texture=string:MODERUNE05.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 94]
	name=string:MODERUNE06
	matGroup=enum:0
	color=color:108 108 108 255
	smoothAngle=float:60
	texture=string:MODERUNE06.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 95]
	name=string:MOSTARMS01
	matGroup=enum:0
	color=color:71 68 59 255
	smoothAngle=float:60
	texture=string:MOSTARMS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 96]
	name=string:MOSTBODY01
	matGroup=enum:0
	color=color:75 71 61 255
	smoothAngle=float:60
	texture=string:MOSTBODY01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 97]
	name=string:MOSTHEAD01
	matGroup=enum:0
	color=color:71 68 59 255
	smoothAngle=float:60
	texture=string:MOSTHEAD01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 98]
	name=string:MOSTLEGS01
	matGroup=enum:0
	color=color:73 69 59 255
	smoothAngle=float:60
	texture=string:MOSTLEGS01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 99]
	name=string:MOSTSARCO
	matGroup=enum:0
	color=color:87 84 74 255
	smoothAngle=float:60
	texture=string:MOSTSARCO.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 100]
	name=string:OTREBORTE01
	matGroup=enum:0
	color=color:117 105 83 255
	smoothAngle=float:60
	texture=string:OTREBORTE01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 101]
	name=string:OTREKRALLE02
	matGroup=enum:0
	color=color:75 67 55 255
	smoothAngle=float:60
	texture=string:OTREKRALLE02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 102]
	name=string:OTRETARGETSTONE_01
	matGroup=enum:0
	color=color:54 48 34 255
	smoothAngle=float:60
	texture=string:OTRETARGETSTONE_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 103]
	name=string:OTRETOMBSTONE
	matGroup=enum:0
	color=color:86 58 78 255
	smoothAngle=float:60
	texture=string:OTRETOMBSTONE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 104]
	name=string:OTWABILDDA01
	matGroup=enum:0
	color=color:69 64 45 255
	smoothAngle=float:60
	texture=string:OTWABILDDA01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 105]
	name=string:OTWABILDDA03
	matGroup=enum:0
	color=color:36 35 28 255
	smoothAngle=float:60
	texture=string:OTWABILDDA03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 106]
	name=string:OTWADAEMONFRESCO
	matGroup=enum:0
	color=color:94 85 61 255
	smoothAngle=float:60
	texture=string:OTWADAEMONFRESCO.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 107]
	name=string:OTWAELEVATOR_01
	matGroup=enum:0
	color=color:104 95 67 255
	smoothAngle=float:60
	texture=string:OTWAELEVATOR_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 108]
	name=string:OTWAMARBEL02 KOPIE
	matGroup=enum:0
	color=color:59 55 46 255
	smoothAngle=float:60
	texture=string:OTWAMARBEL02 KOPIE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 109]
	name=string:OTWAMARBEL02A
	matGroup=enum:0
	color=color:51 48 40 255
	smoothAngle=float:60
	texture=string:OTWAMARBEL02A.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 110]
	name=string:OTWAMASKWATER
	matGroup=enum:0
	color=color:81 80 64 255
	smoothAngle=float:60
	texture=string:OTWAMASKWATER.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 111]
	name=string:OTWAROWOFSYMBOLS1 
	matGroup=enum:0
	color=color:92 82 56 255
	smoothAngle=float:60
	texture=string:OTWAROWOFSYMBOLS1 .TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 112]
	name=string:OTWAROWOFSYMBOLS2 
	matGroup=enum:0
	color=color:92 82 55 255
	smoothAngle=float:60
	texture=string:OTWAROWOFSYMBOLS2 .TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 113]
	name=string:OTWASITALRE1
	matGroup=enum:0
	color=color:102 88 57 255
	smoothAngle=float:60
	texture=string:OTWASITALRE1.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 114]
	name=string:OTWATEMPELDOORFRESCO_02
	matGroup=enum:0
	color=color:104 95 68 255
	smoothAngle=float:60
	texture=string:OTWATEMPELDOORFRESCO_02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 17408 115]
	name=string:OTWATEMPELDOORFRESCO
	matGroup=enum:0
	color=color:106 97 69 255
	smoothAngle=float:60
	texture=string:OTWATEMPELDOORFRESCO.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	defaultMapping=rawFloat:2.34375 2.34375 
[]
